import { findRouteKey, type RouteKey } from "@/i18n/paths";
import type { SupportedLocale } from "@/i18n/locales";

import type { CmsPage } from "./types";

export type DefaultPageSeed = {
  routeKey: RouteKey;
  slug: string;
  title: string;
  summary?: string;
  hero?: {
    eyebrow?: string;
    title?: string;
    lead?: string;
    ctaLabel?: string;
    ctaHref?: string;
  };
  contentHtml: string;
  seoTitle?: string;
  seoDescription?: string;
};

const MINING_FRAUD_CONTENT_FR = `
<p>La fraude minière désigne toute activité illégale visant à extraire, détourner, dissimuler, transporter, acheter ou vendre des substances minérales en violation des lois et règlements en vigueur, notamment le Code minier et le Règlement minier.</p>
<p>Elle constitue l'une des menaces les plus graves contre la souveraineté économique de la République Démocratique du Congo, en privant l'État de ressources essentielles et en alimentant des réseaux criminels organisés.</p>
<p>Selon l'article 4 du Décret n°23/19 du 09 juin 2023, la fraude minière recouvre notamment :</p>
<ul>
  <li>Exploitation clandestine dans des zones non autorisées ou en dehors des périmètres légalement attribués ;</li>
  <li>Détournement de production par des opérateurs ou des tiers ;</li>
  <li>Falsification des documents miniers, y compris certificats, titres, déclarations ou documents de transport ;</li>
  <li>Manipulation des volumes, teneurs ou valeurs déclarées pour réduire artificiellement les obligations fiscales ou parafiscales ;</li>
  <li>Corruption ou collusion impliquant des agents publics ou privés ;</li>
  <li>Exportation dissimulée ou non déclarée de minerais vers des pays voisins ;</li>
  <li>Transmission illicite d'informations stratégiques du secteur minier à des tiers, par voie électronique ou physique ;</li>
  <li>Sous-évaluation volontaire des apports de l'État dans les joint-ventures ou manipulation des prix de transfert.</li>
</ul>
<p>Ces pratiques, expressément visées par le Décret n°23/19, portent atteinte à la transparence, à la traçabilité et à la bonne gouvernance du secteur minier. Elles fragilisent également les communautés locales, qui dépendent des retombées économiques et sociales générées par l'exploitation légale des ressources naturelles.</p>
<p>Conformément à l'article 5 du Décret n°23/19, l'Inspection Générale des Mines mène des opérations régulières de :</p>
<ul>
  <li>Contrôle sur les sites d'exploitation, les comptoirs, les entités de traitement et les corridors logistiques ;</li>
  <li>Investigation pour détecter, documenter et constater les infractions ;</li>
  <li>Sécurisation des substances minérales depuis le site d'extraction jusqu'au point d'exportation ;</li>
  <li>Coordination interservices avec la DGDA, la PNC, la CENAREF, Interpol, le CEEC et d'autres institutions spécialisées.</li>
</ul>
<p>L'IGM joue ainsi un rôle central dans la prévention, la répression et le démantèlement des réseaux de fraude minière, contribuant à la protection des intérêts stratégiques de la Nation et à la consolidation de la gouvernance minière en République Démocratique du Congo.</p>
`.trim();

const MINING_FRAUD_CONTENT_EN = `
<p>Mining fraud refers to any illegal activity aimed at extracting, diverting, concealing, transporting, buying or selling mineral substances in violation of applicable laws and regulations, in particular the Mining Code and Mining Regulations.</p>
<p>It is one of the most serious threats to the economic sovereignty of the Democratic Republic of Congo, depriving the State of essential resources and fuelling organised criminal networks.</p>
<p>Under Article 4 of Decree No. 23/19 of 9 June 2023, mining fraud notably includes:</p>
<ul>
  <li>Clandestine exploitation in unauthorised areas or outside legally allocated perimeters;</li>
  <li>Diversion of production by operators or third parties;</li>
  <li>Forgery of mining documents, including certificates, titles, declarations or transport documents;</li>
  <li>Manipulation of declared volumes, grades or values to artificially reduce tax and parafiscal obligations;</li>
  <li>Corruption or collusion involving public or private agents;</li>
  <li>Concealed or undeclared export of minerals to neighbouring countries;</li>
  <li>Illicit transmission of strategic mining sector information to third parties, electronically or physically;</li>
  <li>Voluntary undervaluation of the State's contributions in joint ventures or transfer pricing manipulation.</li>
</ul>
<p>These practices, expressly covered by Decree No. 23/19, undermine transparency, traceability and good governance in the mining sector. They also weaken local communities that depend on the economic and social benefits generated by lawful exploitation of natural resources.</p>
<p>In accordance with Article 5 of Decree No. 23/19, the General Mine Inspection carries out regular operations involving:</p>
<ul>
  <li>Inspection at mining sites, trading counters, processing entities and logistics corridors;</li>
  <li>Investigation to detect, document and establish offences;</li>
  <li>Securing mineral substances from the extraction site to the export point;</li>
  <li>Inter-agency coordination with DGDA, PNC, CENAREF, Interpol, CEEC and other specialised institutions.</li>
</ul>
<p>IGM thus plays a central role in preventing, repressing and dismantling mining fraud networks, helping to protect the Nation's strategic interests and strengthen mining governance in the Democratic Republic of Congo.</p>
`.trim();

export const DEFAULT_MINING_FRAUD_PAGE_FR: DefaultPageSeed = {
  routeKey: "fraud",
  slug: "fraude-miniere",
  title: "La Fraude minière",
  hero: {
    eyebrow: "LCFCM",
    title: "La Fraude minière",
    lead:
      "Lutte contre les activités illégales visant à détourner, dissimuler ou commercialiser illicitement les substances minérales.",
    ctaLabel: "Dénoncer un cas",
    ctaHref: "/denoncer",
  },
  contentHtml: MINING_FRAUD_CONTENT_FR,
  seoTitle: "La Fraude minière — IGM",
  seoDescription:
    "Définition, formes de fraude minière et rôle de l'IGM dans la prévention, la répression et le démantèlement des réseaux criminels (Décret n°23/19).",
};

export const DEFAULT_MINING_FRAUD_PAGE_EN: DefaultPageSeed = {
  routeKey: "fraud",
  slug: "mining-fraud",
  title: "Mining fraud",
  hero: {
    eyebrow: "LCFCM",
    title: "Mining fraud",
    lead:
      "Combating illegal activities aimed at diverting, concealing or unlawfully trading mineral substances.",
    ctaLabel: "Report a case",
    ctaHref: "/denoncer",
  },
  contentHtml: MINING_FRAUD_CONTENT_EN,
  seoTitle: "Mining fraud — IGM",
  seoDescription:
    "Definition, forms of mining fraud and IGM's role in prevention, enforcement and dismantling criminal networks (Decree No. 23/19).",
};

const MINING_SMUGGLING_CONTENT_FR = `
<p>La contrebande minière désigne toute opération consistant à sortir illégalement du territoire national des substances minérales — brutes, concentrées ou transformées — en échappant aux contrôles douaniers, fiscaux, administratifs et sécuritaires.</p>
<p>Elle constitue une infraction grave qui porte atteinte aux intérêts stratégiques de la République Démocratique du Congo et compromet la traçabilité internationale des minerais congolais.</p>
<p>Selon l'article 4 du Décret n°23/19 du 09 juin 2023, la contrebande minière recouvre notamment :</p>
<ul>
  <li>Le transport clandestin de minerais vers les pays voisins par des voies non autorisées ;</li>
  <li>L'utilisation de pistes, routes ou points de passage non officiels pour contourner les postes de contrôle ;</li>
  <li>La dissimulation ou le camouflage des cargaisons dans des véhicules, conteneurs ou marchandises mixtes ;</li>
  <li>La falsification ou la fabrication de faux documents d'exportation (déclarations, certificats, bordereaux, autorisations) ;</li>
  <li>La complicité de réseaux transfrontaliers impliquant des individus, des groupes organisés ou des opérateurs économiques ;</li>
  <li>Toute transaction visant à soustraire des substances minérales au contrôle légal, en violation du Code minier et du Règlement minier.</li>
</ul>
<p>Ces pratiques entraînent :</p>
<ul>
  <li>Une perte financière majeure pour l'État ;</li>
  <li>Une érosion des recettes publiques ;</li>
  <li>Une rupture de la chaîne de traçabilité ;</li>
  <li>Un risque de sanctions internationales pour non-conformité aux normes de diligence raisonnable (OCDE, CIRGL, ITIE).</li>
</ul>
<p>Conformément aux articles 5, 6, 7 et 8 du Décret n°23/19, l'Inspection Générale des Mines mène des actions coordonnées pour :</p>
<ul>
  <li>Sécuriser les corridors miniers du site d'exploitation jusqu'au point d'exportation ;</li>
  <li>Renforcer les contrôles sur les routes, postes frontaliers, ports et aéroports ;</li>
  <li>Démanteler les réseaux criminels transfrontaliers en collaboration avec :</li>
</ul>
<ul>
  <li>La DGDA ;</li>
  <li>La Police Nationale Congolaise ;</li>
  <li>La CENAREF ;</li>
  <li>Interpol (BCN) ;</li>
  <li>Le CEEC ;</li>
  <li>Les services de sécurité provinciaux ;</li>
  <li>Les autorités des pays voisins.</li>
</ul>
<p>L'IGM joue ainsi un rôle essentiel dans la protection des ressources nationales, la préservation des recettes publiques et la consolidation de la gouvernance minière en République Démocratique du Congo.</p>
`.trim();

const MINING_SMUGGLING_CONTENT_EN = `
<p>Mining smuggling refers to any operation involving the illegal removal from national territory of mineral substances — raw, concentrated or processed — by evading customs, tax, administrative and security controls.</p>
<p>It is a serious offence that undermines the strategic interests of the Democratic Republic of Congo and compromises the international traceability of Congolese minerals.</p>
<p>Under Article 4 of Decree No. 23/19 of 9 June 2023, mining smuggling notably includes:</p>
<ul>
  <li>Clandestine transport of minerals to neighbouring countries via unauthorised routes;</li>
  <li>Use of tracks, roads or unofficial crossing points to bypass control posts;</li>
  <li>Concealment or camouflage of cargo in vehicles, containers or mixed goods;</li>
  <li>Forgery or fabrication of false export documents (declarations, certificates, waybills, authorisations);</li>
  <li>Complicity of cross-border networks involving individuals, organised groups or economic operators;</li>
  <li>Any transaction aimed at removing mineral substances from legal control, in violation of the Mining Code and Mining Regulations.</li>
</ul>
<p>These practices lead to:</p>
<ul>
  <li>Major financial losses for the State;</li>
  <li>Erosion of public revenue;</li>
  <li>Breakdown of the traceability chain;</li>
  <li>Risk of international sanctions for non-compliance with due diligence standards (OECD, ICGLR, EITI).</li>
</ul>
<p>In accordance with Articles 5, 6, 7 and 8 of Decree No. 23/19, the General Mine Inspection carries out coordinated actions to:</p>
<ul>
  <li>Secure mining corridors from the extraction site to the export point;</li>
  <li>Strengthen controls on roads, border posts, ports and airports;</li>
  <li>Dismantle cross-border criminal networks in collaboration with:</li>
</ul>
<ul>
  <li>DGDA;</li>
  <li>Congolese National Police;</li>
  <li>CENAREF;</li>
  <li>Interpol (NCB);</li>
  <li>CEEC;</li>
  <li>Provincial security services;</li>
  <li>Neighbouring countries' authorities.</li>
</ul>
<p>IGM thus plays an essential role in protecting national resources, preserving public revenue and strengthening mining governance in the Democratic Republic of Congo.</p>
`.trim();

export const DEFAULT_MINING_SMUGGLING_PAGE_FR: DefaultPageSeed = {
  routeKey: "smuggling",
  slug: "contrebande-miniere",
  title: "La Contrebande minière",
  hero: {
    eyebrow: "LCFCM",
    title: "La Contrebande minière",
    lead:
      "Lutte contre l'exfiltration illégale de substances minérales hors du territoire national, en contournant les contrôles douaniers et sécuritaires.",
    ctaLabel: "Dénoncer un cas",
    ctaHref: "/denoncer",
  },
  contentHtml: MINING_SMUGGLING_CONTENT_FR,
  seoTitle: "La Contrebande minière — IGM",
  seoDescription:
    "Définition, formes de contrebande minière et rôle de l'IGM dans la sécurisation des corridors et le démantèlement des réseaux transfrontaliers (Décret n°23/19).",
};

export const DEFAULT_MINING_SMUGGLING_PAGE_EN: DefaultPageSeed = {
  routeKey: "smuggling",
  slug: "mining-smuggling",
  title: "Mining smuggling",
  hero: {
    eyebrow: "LCFCM",
    title: "Mining smuggling",
    lead:
      "Combating the illegal removal of mineral substances from national territory by evading customs and security controls.",
    ctaLabel: "Report a case",
    ctaHref: "/denoncer",
  },
  contentHtml: MINING_SMUGGLING_CONTENT_EN,
  seoTitle: "Mining smuggling — IGM",
  seoDescription:
    "Definition, forms of mining smuggling and IGM's role in securing corridors and dismantling cross-border networks (Decree No. 23/19).",
};

const SANCTIONS_CONTENT_FR = `
<p>Le secteur minier en République Démocratique du Congo est régi par un ensemble de règles strictes visant à garantir la transparence, la traçabilité, la protection de l'environnement, la sécurité des opérations et la préservation des ressources naturelles.</p>
<p>Le Code minier (Loi n°007/2002 modifiée par la Loi n°18/001 du 09 mars 2018) et le Règlement minier (Décret n°038/2003 modifié par Décret n°18/024 du 08 juin 2018) prévoient un régime complet de sanctions administratives, civiles et pénales applicables aux opérateurs, aux personnes physiques et aux entités impliquées dans des activités minières.</p>
<p>Selon ces textes, les sanctions visent à réprimer :</p>
<ul>
  <li>Les manquements aux obligations techniques (articles 195 à 207 du Code minier) ;</li>
  <li>Les violations environnementales, notamment celles visées à l'article 306 du Code minier ;</li>
  <li>Le non-respect des obligations sociales prévues dans les cahiers des charges ;</li>
  <li>La fraude et la contrebande minières, définies à l'article 4 du Décret n°23/19 du 09 juin 2023 ;</li>
  <li>L'exploitation illégale sans titre ou en dehors des périmètres autorisés (articles 299 à 311 du Code minier) ;</li>
  <li>L'entrave aux missions de contrôle de l'État, y compris l'obstruction aux inspections de l'IGM.</li>
</ul>
<p>Les sanctions prévues par le Code minier et le Règlement minier peuvent prendre plusieurs formes, notamment :</p>
<ul>
  <li>Amendes administratives et pénales pouvant atteindre plusieurs millions de dollars selon la gravité de l'infraction (articles 299 à 311 du Code minier) ;</li>
  <li>Servitudes pénales pour les infractions graves, dont la fraude, la contrebande ou l'exploitation illégale ;</li>
  <li>Suspension ou retrait du droit minier en cas de manquements répétés ou graves (articles 202, 203 et 204 du Code minier) ;</li>
  <li>Saisie des substances minérales issues d'activités illicites, conformément au Règlement minier ;</li>
  <li>Fermeture temporaire ou définitive du site en cas de danger, de non-conformité ou d'infractions graves ;</li>
  <li>Poursuites judiciaires engagées par les autorités compétentes.</li>
</ul>
<p>Certaines infractions, notamment la fraude et la contrebande minières, sont expressément définies et réprimées par le Décret n°23/19 du 09 juin 2023, qui renforce le dispositif national de lutte contre les activités illicites dans le secteur minier.</p>
<p>Conformément aux articles 5, 6, 7 et 8 du Décret n°23/19, l'Inspection Générale des Mines joue un rôle central dans :</p>
<ul>
  <li>Le constat des infractions sur les sites miniers, dans les comptoirs et le long des corridors logistiques ;</li>
  <li>La documentation et la qualification des faits conformément aux exigences du Code minier ;</li>
  <li>La transmission des dossiers aux autorités judiciaires, administratives ou fiscales compétentes ;</li>
  <li>Le suivi des procédures jusqu'à l'application effective des sanctions ;</li>
  <li>La coordination interservices avec la DGDA, la PNC, la CENAREF, Interpol, le CEEC et les provinces.</li>
</ul>
<p>Grâce à son mandat légal, l'IGM garantit que les opérateurs miniers respectent les normes nationales, les standards internationaux et les principes de bonne gouvernance, contribuant ainsi à la protection des ressources naturelles et à la consolidation de l'État de droit dans le secteur minier.</p>
`.trim();

const SANCTIONS_CONTENT_EN = `
<p>The mining sector in the Democratic Republic of Congo is governed by strict rules aimed at ensuring transparency, traceability, environmental protection, operational safety and preservation of natural resources.</p>
<p>The Mining Code (Law No. 007/2002 as amended by Law No. 18/001 of 9 March 2018) and Mining Regulations (Decree No. 038/2003 as amended by Decree No. 18/024 of 8 June 2018) provide a comprehensive regime of administrative, civil and criminal sanctions applicable to operators, individuals and entities involved in mining activities.</p>
<p>Under these texts, sanctions aim to punish:</p>
<ul>
  <li>Failure to meet technical obligations (Articles 195 to 207 of the Mining Code);</li>
  <li>Environmental violations, including those covered by Article 306 of the Mining Code;</li>
  <li>Non-compliance with social obligations set out in mining agreements;</li>
  <li>Mining fraud and smuggling, as defined in Article 4 of Decree No. 23/19 of 9 June 2023;</li>
  <li>Illegal exploitation without a title or outside authorised perimeters (Articles 299 to 311 of the Mining Code);</li>
  <li>Obstruction of State control missions, including obstruction of IGM inspections.</li>
</ul>
<p>Sanctions under the Mining Code and Mining Regulations may take several forms, including:</p>
<ul>
  <li>Administrative and criminal fines that may reach several million dollars depending on the severity of the offence (Articles 299 to 311 of the Mining Code);</li>
  <li>Penal servitude for serious offences, including fraud, smuggling or illegal exploitation;</li>
  <li>Suspension or withdrawal of mining rights in cases of repeated or serious breaches (Articles 202, 203 and 204 of the Mining Code);</li>
  <li>Seizure of mineral substances from illicit activities, in accordance with Mining Regulations;</li>
  <li>Temporary or permanent closure of a site in cases of danger, non-compliance or serious offences;</li>
  <li>Legal proceedings initiated by the competent authorities.</li>
</ul>
<p>Certain offences, particularly mining fraud and smuggling, are expressly defined and punished by Decree No. 23/19 of 9 June 2023, which strengthens the national framework for combating illicit activities in the mining sector.</p>
<p>In accordance with Articles 5, 6, 7 and 8 of Decree No. 23/19, the General Mine Inspection plays a central role in:</p>
<ul>
  <li>Establishing offences at mining sites, trading counters and along logistics corridors;</li>
  <li>Documenting and qualifying facts in accordance with Mining Code requirements;</li>
  <li>Transmitting case files to competent judicial, administrative or tax authorities;</li>
  <li>Monitoring procedures through to effective application of sanctions;</li>
  <li>Inter-agency coordination with DGDA, PNC, CENAREF, Interpol, CEEC and provincial authorities.</li>
</ul>
<p>Through its legal mandate, IGM ensures that mining operators comply with national standards, international standards and good governance principles, thereby helping to protect natural resources and strengthen the rule of law in the mining sector.</p>
`.trim();

export const DEFAULT_SANCTIONS_PAGE_FR: DefaultPageSeed = {
  routeKey: "sanctions",
  slug: "sanctions",
  title: "Les Sanctions",
  hero: {
    eyebrow: "LCFCM",
    title: "Les Sanctions",
    lead:
      "Cadre réglementaire des sanctions administratives, civiles et pénales applicables aux activités minières en RDC.",
    ctaLabel: "Dénoncer un cas",
    ctaHref: "/denoncer",
  },
  contentHtml: SANCTIONS_CONTENT_FR,
  seoTitle: "Les Sanctions dans le secteur minier — IGM",
  seoDescription:
    "Régime des sanctions minières en RDC : Code minier, Règlement minier et rôle de l'IGM dans le constat des infractions et le suivi des procédures.",
};

export const DEFAULT_SANCTIONS_PAGE_EN: DefaultPageSeed = {
  routeKey: "sanctions",
  slug: "sanctions",
  title: "Sanctions",
  hero: {
    eyebrow: "LCFCM",
    title: "Sanctions",
    lead:
      "Regulatory framework for administrative, civil and criminal sanctions applicable to mining activities in the DRC.",
    ctaLabel: "Report a case",
    ctaHref: "/denoncer",
  },
  contentHtml: SANCTIONS_CONTENT_EN,
  seoTitle: "Sanctions in the mining sector — IGM",
  seoDescription:
    "Mining sanctions regime in the DRC: Mining Code, Mining Regulations and IGM's role in establishing offences and monitoring procedures.",
};

const DEFAULT_PAGES_BY_LOCALE = {
  fr: [DEFAULT_MINING_FRAUD_PAGE_FR, DEFAULT_MINING_SMUGGLING_PAGE_FR, DEFAULT_SANCTIONS_PAGE_FR],
  en: [DEFAULT_MINING_FRAUD_PAGE_EN, DEFAULT_MINING_SMUGGLING_PAGE_EN, DEFAULT_SANCTIONS_PAGE_EN],
} satisfies Record<SupportedLocale, DefaultPageSeed[]>;

export function getDefaultPageSeed(slug: string, locale: SupportedLocale): DefaultPageSeed | null {
  const routeKey = findRouteKey(slug, locale);
  if (!routeKey) return null;

  return DEFAULT_PAGES_BY_LOCALE[locale].find((page) => page.routeKey === routeKey) ?? null;
}

export function defaultPageToCmsPage(seed: DefaultPageSeed): CmsPage {
  return {
    id: 0,
    slug: seed.slug,
    title: seed.title,
    summary: seed.summary ?? null,
    hero: seed.hero ?? undefined,
    contentHtml: seed.contentHtml,
    seoTitle: seed.seoTitle ?? null,
    seoDescription: seed.seoDescription ?? null,
  };
}

export function mergePageWithDefault(page: CmsPage | null, slug: string, locale: SupportedLocale): CmsPage | null {
  const fallback = getDefaultPageSeed(slug, locale);
  if (!fallback) return page;

  const base = defaultPageToCmsPage(fallback);

  if (!page) return base;

  const hasContent = Boolean(page.contentHtml?.trim() || page.summary?.trim());
  if (!hasContent) {
    return {
      ...page,
      title: page.title?.trim() || base.title,
      summary: page.summary?.trim() || base.summary,
      hero: page.hero?.title?.trim() ? page.hero : base.hero,
      contentHtml: base.contentHtml,
      seoTitle: page.seoTitle?.trim() || base.seoTitle,
      seoDescription: page.seoDescription?.trim() || base.seoDescription,
    };
  }

  return page;
}

export const DEFAULT_PAGE_SEED_PAIRS = [
  { fr: DEFAULT_MINING_FRAUD_PAGE_FR, en: DEFAULT_MINING_FRAUD_PAGE_EN },
  { fr: DEFAULT_MINING_SMUGGLING_PAGE_FR, en: DEFAULT_MINING_SMUGGLING_PAGE_EN },
  { fr: DEFAULT_SANCTIONS_PAGE_FR, en: DEFAULT_SANCTIONS_PAGE_EN },
] as const;
