import { findRouteKey, type RouteKey } from "@/i18n/paths";
import type { SupportedLocale } from "@/i18n/locales";

import type { CmsPage } from "./types";

export type DefaultPageSeed = {
  routeKey: RouteKey;
  slug: string;
  title: string;
  summary?: string;
  hero?: {
    eyebrow?: string;
    title?: string;
    lead?: string;
    ctaLabel?: string;
    ctaHref?: string;
  };
  contentHtml: string;
  seoTitle?: string;
  seoDescription?: string;
};

const MINING_FRAUD_CONTENT_FR = `
<p>La fraude minière désigne toute activité illégale visant à extraire, détourner, dissimuler, transporter, acheter ou vendre des substances minérales en violation des lois et règlements en vigueur, notamment le Code minier et le Règlement minier.</p>
<p>Elle constitue l'une des menaces les plus graves contre la souveraineté économique de la République Démocratique du Congo, en privant l'État de ressources essentielles et en alimentant des réseaux criminels organisés.</p>
<p>Selon l'article 4 du Décret n°23/19 du 09 juin 2023, la fraude minière recouvre notamment :</p>
<ul>
  <li>Exploitation clandestine dans des zones non autorisées ou en dehors des périmètres légalement attribués ;</li>
  <li>Détournement de production par des opérateurs ou des tiers ;</li>
  <li>Falsification des documents miniers, y compris certificats, titres, déclarations ou documents de transport ;</li>
  <li>Manipulation des volumes, teneurs ou valeurs déclarées pour réduire artificiellement les obligations fiscales ou parafiscales ;</li>
  <li>Corruption ou collusion impliquant des agents publics ou privés ;</li>
  <li>Exportation dissimulée ou non déclarée de minerais vers des pays voisins ;</li>
  <li>Transmission illicite d'informations stratégiques du secteur minier à des tiers, par voie électronique ou physique ;</li>
  <li>Sous-évaluation volontaire des apports de l'État dans les joint-ventures ou manipulation des prix de transfert.</li>
</ul>
<p>Ces pratiques, expressément visées par le Décret n°23/19, portent atteinte à la transparence, à la traçabilité et à la bonne gouvernance du secteur minier. Elles fragilisent également les communautés locales, qui dépendent des retombées économiques et sociales générées par l'exploitation légale des ressources naturelles.</p>
<p>Conformément à l'article 5 du Décret n°23/19, l'Inspection Générale des Mines mène des opérations régulières de :</p>
<ul>
  <li>Contrôle sur les sites d'exploitation, les comptoirs, les entités de traitement et les corridors logistiques ;</li>
  <li>Investigation pour détecter, documenter et constater les infractions ;</li>
  <li>Sécurisation des substances minérales depuis le site d'extraction jusqu'au point d'exportation ;</li>
  <li>Coordination interservices avec la DGDA, la PNC, la CENAREF, Interpol, le CEEC et d'autres institutions spécialisées.</li>
</ul>
<p>L'IGM joue ainsi un rôle central dans la prévention, la répression et le démantèlement des réseaux de fraude minière, contribuant à la protection des intérêts stratégiques de la Nation et à la consolidation de la gouvernance minière en République Démocratique du Congo.</p>
`.trim();

const MINING_FRAUD_CONTENT_EN = `
<p>Mining fraud refers to any illegal activity aimed at extracting, diverting, concealing, transporting, buying or selling mineral substances in violation of applicable laws and regulations, in particular the Mining Code and Mining Regulations.</p>
<p>It is one of the most serious threats to the economic sovereignty of the Democratic Republic of Congo, depriving the State of essential resources and fuelling organised criminal networks.</p>
<p>Under Article 4 of Decree No. 23/19 of 9 June 2023, mining fraud notably includes:</p>
<ul>
  <li>Clandestine exploitation in unauthorised areas or outside legally allocated perimeters;</li>
  <li>Diversion of production by operators or third parties;</li>
  <li>Forgery of mining documents, including certificates, titles, declarations or transport documents;</li>
  <li>Manipulation of declared volumes, grades or values to artificially reduce tax and parafiscal obligations;</li>
  <li>Corruption or collusion involving public or private agents;</li>
  <li>Concealed or undeclared export of minerals to neighbouring countries;</li>
  <li>Illicit transmission of strategic mining sector information to third parties, electronically or physically;</li>
  <li>Voluntary undervaluation of the State's contributions in joint ventures or transfer pricing manipulation.</li>
</ul>
<p>These practices, expressly covered by Decree No. 23/19, undermine transparency, traceability and good governance in the mining sector. They also weaken local communities that depend on the economic and social benefits generated by lawful exploitation of natural resources.</p>
<p>In accordance with Article 5 of Decree No. 23/19, the General Mine Inspection carries out regular operations involving:</p>
<ul>
  <li>Inspection at mining sites, trading counters, processing entities and logistics corridors;</li>
  <li>Investigation to detect, document and establish offences;</li>
  <li>Securing mineral substances from the extraction site to the export point;</li>
  <li>Inter-agency coordination with DGDA, PNC, CENAREF, Interpol, CEEC and other specialised institutions.</li>
</ul>
<p>IGM thus plays a central role in preventing, repressing and dismantling mining fraud networks, helping to protect the Nation's strategic interests and strengthen mining governance in the Democratic Republic of Congo.</p>
`.trim();

export const DEFAULT_MINING_FRAUD_PAGE_FR: DefaultPageSeed = {
  routeKey: "fraud",
  slug: "fraude-miniere",
  title: "La Fraude minière",
  hero: {
    eyebrow: "LCFCM",
    title: "La Fraude minière",
    lead:
      "Lutte contre les activités illégales visant à détourner, dissimuler ou commercialiser illicitement les substances minérales.",
    ctaLabel: "Dénoncer un cas",
    ctaHref: "/denoncer",
  },
  contentHtml: MINING_FRAUD_CONTENT_FR,
  seoTitle: "La Fraude minière — IGM",
  seoDescription:
    "Définition, formes de fraude minière et rôle de l'IGM dans la prévention, la répression et le démantèlement des réseaux criminels (Décret n°23/19).",
};

export const DEFAULT_MINING_FRAUD_PAGE_EN: DefaultPageSeed = {
  routeKey: "fraud",
  slug: "mining-fraud",
  title: "Mining fraud",
  hero: {
    eyebrow: "LCFCM",
    title: "Mining fraud",
    lead:
      "Combating illegal activities aimed at diverting, concealing or unlawfully trading mineral substances.",
    ctaLabel: "Report a case",
    ctaHref: "/denoncer",
  },
  contentHtml: MINING_FRAUD_CONTENT_EN,
  seoTitle: "Mining fraud — IGM",
  seoDescription:
    "Definition, forms of mining fraud and IGM's role in prevention, enforcement and dismantling criminal networks (Decree No. 23/19).",
};

const MINING_SMUGGLING_CONTENT_FR = `
<p>La contrebande minière désigne toute opération consistant à sortir illégalement du territoire national des substances minérales — brutes, concentrées ou transformées — en échappant aux contrôles douaniers, fiscaux, administratifs et sécuritaires.</p>
<p>Elle constitue une infraction grave qui porte atteinte aux intérêts stratégiques de la République Démocratique du Congo et compromet la traçabilité internationale des minerais congolais.</p>
<p>Selon l'article 4 du Décret n°23/19 du 09 juin 2023, la contrebande minière recouvre notamment :</p>
<ul>
  <li>Le transport clandestin de minerais vers les pays voisins par des voies non autorisées ;</li>
  <li>L'utilisation de pistes, routes ou points de passage non officiels pour contourner les postes de contrôle ;</li>
  <li>La dissimulation ou le camouflage des cargaisons dans des véhicules, conteneurs ou marchandises mixtes ;</li>
  <li>La falsification ou la fabrication de faux documents d'exportation (déclarations, certificats, bordereaux, autorisations) ;</li>
  <li>La complicité de réseaux transfrontaliers impliquant des individus, des groupes organisés ou des opérateurs économiques ;</li>
  <li>Toute transaction visant à soustraire des substances minérales au contrôle légal, en violation du Code minier et du Règlement minier.</li>
</ul>
<p>Ces pratiques entraînent :</p>
<ul>
  <li>Une perte financière majeure pour l'État ;</li>
  <li>Une érosion des recettes publiques ;</li>
  <li>Une rupture de la chaîne de traçabilité ;</li>
  <li>Un risque de sanctions internationales pour non-conformité aux normes de diligence raisonnable (OCDE, CIRGL, ITIE).</li>
</ul>
<p>Conformément aux articles 5, 6, 7 et 8 du Décret n°23/19, l'Inspection Générale des Mines mène des actions coordonnées pour :</p>
<ul>
  <li>Sécuriser les corridors miniers du site d'exploitation jusqu'au point d'exportation ;</li>
  <li>Renforcer les contrôles sur les routes, postes frontaliers, ports et aéroports ;</li>
  <li>Démanteler les réseaux criminels transfrontaliers en collaboration avec :</li>
</ul>
<ul>
  <li>La DGDA ;</li>
  <li>La Police Nationale Congolaise ;</li>
  <li>La CENAREF ;</li>
  <li>Interpol (BCN) ;</li>
  <li>Le CEEC ;</li>
  <li>Les services de sécurité provinciaux ;</li>
  <li>Les autorités des pays voisins.</li>
</ul>
<p>L'IGM joue ainsi un rôle essentiel dans la protection des ressources nationales, la préservation des recettes publiques et la consolidation de la gouvernance minière en République Démocratique du Congo.</p>
`.trim();

const MINING_SMUGGLING_CONTENT_EN = `
<p>Mining smuggling refers to any operation involving the illegal removal from national territory of mineral substances — raw, concentrated or processed — by evading customs, tax, administrative and security controls.</p>
<p>It is a serious offence that undermines the strategic interests of the Democratic Republic of Congo and compromises the international traceability of Congolese minerals.</p>
<p>Under Article 4 of Decree No. 23/19 of 9 June 2023, mining smuggling notably includes:</p>
<ul>
  <li>Clandestine transport of minerals to neighbouring countries via unauthorised routes;</li>
  <li>Use of tracks, roads or unofficial crossing points to bypass control posts;</li>
  <li>Concealment or camouflage of cargo in vehicles, containers or mixed goods;</li>
  <li>Forgery or fabrication of false export documents (declarations, certificates, waybills, authorisations);</li>
  <li>Complicity of cross-border networks involving individuals, organised groups or economic operators;</li>
  <li>Any transaction aimed at removing mineral substances from legal control, in violation of the Mining Code and Mining Regulations.</li>
</ul>
<p>These practices lead to:</p>
<ul>
  <li>Major financial losses for the State;</li>
  <li>Erosion of public revenue;</li>
  <li>Breakdown of the traceability chain;</li>
  <li>Risk of international sanctions for non-compliance with due diligence standards (OECD, ICGLR, EITI).</li>
</ul>
<p>In accordance with Articles 5, 6, 7 and 8 of Decree No. 23/19, the General Mine Inspection carries out coordinated actions to:</p>
<ul>
  <li>Secure mining corridors from the extraction site to the export point;</li>
  <li>Strengthen controls on roads, border posts, ports and airports;</li>
  <li>Dismantle cross-border criminal networks in collaboration with:</li>
</ul>
<ul>
  <li>DGDA;</li>
  <li>Congolese National Police;</li>
  <li>CENAREF;</li>
  <li>Interpol (NCB);</li>
  <li>CEEC;</li>
  <li>Provincial security services;</li>
  <li>Neighbouring countries' authorities.</li>
</ul>
<p>IGM thus plays an essential role in protecting national resources, preserving public revenue and strengthening mining governance in the Democratic Republic of Congo.</p>
`.trim();

export const DEFAULT_MINING_SMUGGLING_PAGE_FR: DefaultPageSeed = {
  routeKey: "smuggling",
  slug: "contrebande-miniere",
  title: "La Contrebande minière",
  hero: {
    eyebrow: "LCFCM",
    title: "La Contrebande minière",
    lead:
      "Lutte contre l'exfiltration illégale de substances minérales hors du territoire national, en contournant les contrôles douaniers et sécuritaires.",
    ctaLabel: "Dénoncer un cas",
    ctaHref: "/denoncer",
  },
  contentHtml: MINING_SMUGGLING_CONTENT_FR,
  seoTitle: "La Contrebande minière — IGM",
  seoDescription:
    "Définition, formes de contrebande minière et rôle de l'IGM dans la sécurisation des corridors et le démantèlement des réseaux transfrontaliers (Décret n°23/19).",
};

export const DEFAULT_MINING_SMUGGLING_PAGE_EN: DefaultPageSeed = {
  routeKey: "smuggling",
  slug: "mining-smuggling",
  title: "Mining smuggling",
  hero: {
    eyebrow: "LCFCM",
    title: "Mining smuggling",
    lead:
      "Combating the illegal removal of mineral substances from national territory by evading customs and security controls.",
    ctaLabel: "Report a case",
    ctaHref: "/denoncer",
  },
  contentHtml: MINING_SMUGGLING_CONTENT_EN,
  seoTitle: "Mining smuggling — IGM",
  seoDescription:
    "Definition, forms of mining smuggling and IGM's role in securing corridors and dismantling cross-border networks (Decree No. 23/19).",
};

const SANCTIONS_CONTENT_FR = `
<p>Le secteur minier en République Démocratique du Congo est régi par un ensemble de règles strictes visant à garantir la transparence, la traçabilité, la protection de l'environnement, la sécurité des opérations et la préservation des ressources naturelles.</p>
<p>Le Code minier (Loi n°007/2002 modifiée par la Loi n°18/001 du 09 mars 2018) et le Règlement minier (Décret n°038/2003 modifié par Décret n°18/024 du 08 juin 2018) prévoient un régime complet de sanctions administratives, civiles et pénales applicables aux opérateurs, aux personnes physiques et aux entités impliquées dans des activités minières.</p>
<p>Selon ces textes, les sanctions visent à réprimer :</p>
<ul>
  <li>Les manquements aux obligations techniques (articles 195 à 207 du Code minier) ;</li>
  <li>Les violations environnementales, notamment celles visées à l'article 306 du Code minier ;</li>
  <li>Le non-respect des obligations sociales prévues dans les cahiers des charges ;</li>
  <li>La fraude et la contrebande minières, définies à l'article 4 du Décret n°23/19 du 09 juin 2023 ;</li>
  <li>L'exploitation illégale sans titre ou en dehors des périmètres autorisés (articles 299 à 311 du Code minier) ;</li>
  <li>L'entrave aux missions de contrôle de l'État, y compris l'obstruction aux inspections de l'IGM.</li>
</ul>
<p>Les sanctions prévues par le Code minier et le Règlement minier peuvent prendre plusieurs formes, notamment :</p>
<ul>
  <li>Amendes administratives et pénales pouvant atteindre plusieurs millions de dollars selon la gravité de l'infraction (articles 299 à 311 du Code minier) ;</li>
  <li>Servitudes pénales pour les infractions graves, dont la fraude, la contrebande ou l'exploitation illégale ;</li>
  <li>Suspension ou retrait du droit minier en cas de manquements répétés ou graves (articles 202, 203 et 204 du Code minier) ;</li>
  <li>Saisie des substances minérales issues d'activités illicites, conformément au Règlement minier ;</li>
  <li>Fermeture temporaire ou définitive du site en cas de danger, de non-conformité ou d'infractions graves ;</li>
  <li>Poursuites judiciaires engagées par les autorités compétentes.</li>
</ul>
<p>Certaines infractions, notamment la fraude et la contrebande minières, sont expressément définies et réprimées par le Décret n°23/19 du 09 juin 2023, qui renforce le dispositif national de lutte contre les activités illicites dans le secteur minier.</p>
<p>Conformément aux articles 5, 6, 7 et 8 du Décret n°23/19, l'Inspection Générale des Mines joue un rôle central dans :</p>
<ul>
  <li>Le constat des infractions sur les sites miniers, dans les comptoirs et le long des corridors logistiques ;</li>
  <li>La documentation et la qualification des faits conformément aux exigences du Code minier ;</li>
  <li>La transmission des dossiers aux autorités judiciaires, administratives ou fiscales compétentes ;</li>
  <li>Le suivi des procédures jusqu'à l'application effective des sanctions ;</li>
  <li>La coordination interservices avec la DGDA, la PNC, la CENAREF, Interpol, le CEEC et les provinces.</li>
</ul>
<p>Grâce à son mandat légal, l'IGM garantit que les opérateurs miniers respectent les normes nationales, les standards internationaux et les principes de bonne gouvernance, contribuant ainsi à la protection des ressources naturelles et à la consolidation de l'État de droit dans le secteur minier.</p>
`.trim();

const SANCTIONS_CONTENT_EN = `
<p>The mining sector in the Democratic Republic of Congo is governed by strict rules aimed at ensuring transparency, traceability, environmental protection, operational safety and preservation of natural resources.</p>
<p>The Mining Code (Law No. 007/2002 as amended by Law No. 18/001 of 9 March 2018) and Mining Regulations (Decree No. 038/2003 as amended by Decree No. 18/024 of 8 June 2018) provide a comprehensive regime of administrative, civil and criminal sanctions applicable to operators, individuals and entities involved in mining activities.</p>
<p>Under these texts, sanctions aim to punish:</p>
<ul>
  <li>Failure to meet technical obligations (Articles 195 to 207 of the Mining Code);</li>
  <li>Environmental violations, including those covered by Article 306 of the Mining Code;</li>
  <li>Non-compliance with social obligations set out in mining agreements;</li>
  <li>Mining fraud and smuggling, as defined in Article 4 of Decree No. 23/19 of 9 June 2023;</li>
  <li>Illegal exploitation without a title or outside authorised perimeters (Articles 299 to 311 of the Mining Code);</li>
  <li>Obstruction of State control missions, including obstruction of IGM inspections.</li>
</ul>
<p>Sanctions under the Mining Code and Mining Regulations may take several forms, including:</p>
<ul>
  <li>Administrative and criminal fines that may reach several million dollars depending on the severity of the offence (Articles 299 to 311 of the Mining Code);</li>
  <li>Penal servitude for serious offences, including fraud, smuggling or illegal exploitation;</li>
  <li>Suspension or withdrawal of mining rights in cases of repeated or serious breaches (Articles 202, 203 and 204 of the Mining Code);</li>
  <li>Seizure of mineral substances from illicit activities, in accordance with Mining Regulations;</li>
  <li>Temporary or permanent closure of a site in cases of danger, non-compliance or serious offences;</li>
  <li>Legal proceedings initiated by the competent authorities.</li>
</ul>
<p>Certain offences, particularly mining fraud and smuggling, are expressly defined and punished by Decree No. 23/19 of 9 June 2023, which strengthens the national framework for combating illicit activities in the mining sector.</p>
<p>In accordance with Articles 5, 6, 7 and 8 of Decree No. 23/19, the General Mine Inspection plays a central role in:</p>
<ul>
  <li>Establishing offences at mining sites, trading counters and along logistics corridors;</li>
  <li>Documenting and qualifying facts in accordance with Mining Code requirements;</li>
  <li>Transmitting case files to competent judicial, administrative or tax authorities;</li>
  <li>Monitoring procedures through to effective application of sanctions;</li>
  <li>Inter-agency coordination with DGDA, PNC, CENAREF, Interpol, CEEC and provincial authorities.</li>
</ul>
<p>Through its legal mandate, IGM ensures that mining operators comply with national standards, international standards and good governance principles, thereby helping to protect natural resources and strengthen the rule of law in the mining sector.</p>
`.trim();

export const DEFAULT_SANCTIONS_PAGE_FR: DefaultPageSeed = {
  routeKey: "sanctions",
  slug: "sanctions",
  title: "Les Sanctions",
  hero: {
    eyebrow: "LCFCM",
    title: "Les Sanctions",
    lead:
      "Cadre réglementaire des sanctions administratives, civiles et pénales applicables aux activités minières en RDC.",
    ctaLabel: "Dénoncer un cas",
    ctaHref: "/denoncer",
  },
  contentHtml: SANCTIONS_CONTENT_FR,
  seoTitle: "Les Sanctions dans le secteur minier — IGM",
  seoDescription:
    "Régime des sanctions minières en RDC : Code minier, Règlement minier et rôle de l'IGM dans le constat des infractions et le suivi des procédures.",
};

export const DEFAULT_SANCTIONS_PAGE_EN: DefaultPageSeed = {
  routeKey: "sanctions",
  slug: "sanctions",
  title: "Sanctions",
  hero: {
    eyebrow: "LCFCM",
    title: "Sanctions",
    lead:
      "Regulatory framework for administrative, civil and criminal sanctions applicable to mining activities in the DRC.",
    ctaLabel: "Report a case",
    ctaHref: "/denoncer",
  },
  contentHtml: SANCTIONS_CONTENT_EN,
  seoTitle: "Sanctions in the mining sector — IGM",
  seoDescription:
    "Mining sanctions regime in the DRC: Mining Code, Mining Regulations and IGM's role in establishing offences and monitoring procedures.",
};

const TERMS_CONTENT_FR = `
<p>Les présentes conditions générales définissent les modalités d'accès et d'utilisation du site officiel de l'Inspection Générale des Mines (IGM), service public spécialisé de l'État congolais créé par le Décret n°23/19 du 09 juin 2023.</p>
<p>En accédant au site et en le consultant, l'utilisateur reconnaît avoir pris connaissance des présentes conditions et s'engage à les respecter.</p>
<p>Le site de l'IGM a pour vocation :</p>
<ul>
  <li>D'informer le public sur les missions, l'organisation et les activités de l'Inspection Générale des Mines ;</li>
  <li>De diffuser les textes légaux et réglementaires applicables au secteur minier en République Démocratique du Congo ;</li>
  <li>De publier les actualités institutionnelles de l'IGM ;</li>
  <li>De permettre le signalement de cas présumés de fraude ou de contrebande minières via le formulaire dédié ;</li>
  <li>De faciliter la prise de contact avec les services de l'IGM.</li>
</ul>
<p>L'ensemble des contenus publiés sur le site — textes, logos, images, documents, vidéos et éléments graphiques — est protégé par les dispositions relatives à la propriété intellectuelle. Toute reproduction, représentation ou diffusion, totale ou partielle, à des fins commerciales est interdite sans autorisation préalable et écrite de l'IGM. La citation des contenus à des fins d'information, d'étude ou de recherche est autorisée sous réserve de mentionner la source.</p>
<p>L'utilisateur s'engage à :</p>
<ul>
  <li>Utiliser le site conformément à sa destination et aux lois en vigueur en République Démocratique du Congo ;</li>
  <li>Ne pas entraver le fonctionnement du site ni tenter d'accéder de manière non autorisée à ses systèmes ;</li>
  <li>Fournir des informations exactes et de bonne foi lors de l'utilisation des formulaires de contact ou de signalement ;</li>
  <li>Ne pas utiliser le formulaire de signalement à des fins de dénonciation calomnieuse, de diffamation ou de harcèlement.</li>
</ul>
<p>Les signalements transmis via la plateforme sont traités de manière confidentielle. L'utilisateur peut choisir de signaler de façon anonyme. Les informations communiquées sont utilisées exclusivement dans le cadre des missions légales de l'IGM en matière de lutte contre la fraude et la contrebande minières.</p>
<p>L'IGM s'efforce d'assurer l'exactitude et la mise à jour des informations publiées. Toutefois, les contenus sont fournis à titre informatif et ne sauraient engager la responsabilité de l'IGM en cas d'erreur, d'omission ou d'indisponibilité temporaire du site. Seuls les textes officiels publiés au Journal Officiel font foi.</p>
<p>Le site peut contenir des liens vers des sites tiers, notamment des institutions partenaires. L'IGM n'exerce aucun contrôle sur ces sites et décline toute responsabilité quant à leurs contenus.</p>
<p>L'IGM se réserve le droit de modifier les présentes conditions générales à tout moment. Les conditions applicables sont celles en vigueur à la date de consultation du site. Les présentes conditions sont régies par le droit congolais ; tout litige relatif à leur application relève de la compétence des juridictions de la République Démocratique du Congo.</p>
<p>Pour toute question relative aux présentes conditions générales ou à l'utilisation du site, vous pouvez contacter l'Inspection Générale des Mines via la page contact ou aux coordonnées officielles indiquées sur le site.</p>
`.trim();

const TERMS_CONTENT_EN = `
<p>These terms and conditions define the terms of access and use of the official website of the General Inspectorate of Mines (IGM), a specialised public service of the Congolese State created by Decree No. 23/19 of 9 June 2023.</p>
<p>By accessing and browsing the site, users acknowledge that they have read these terms and agree to comply with them.</p>
<p>The IGM website is intended to:</p>
<ul>
  <li>Inform the public about the missions, organisation and activities of the General Inspectorate of Mines;</li>
  <li>Disseminate the legal and regulatory texts applicable to the mining sector in the Democratic Republic of Congo;</li>
  <li>Publish IGM institutional news;</li>
  <li>Enable the reporting of suspected cases of mining fraud or smuggling via the dedicated form;</li>
  <li>Facilitate contact with IGM services.</li>
</ul>
<p>All content published on the site — texts, logos, images, documents, videos and graphic elements — is protected by intellectual property provisions. Any reproduction, representation or distribution, in whole or in part, for commercial purposes is prohibited without the prior written authorisation of IGM. Quoting content for information, study or research purposes is permitted provided the source is acknowledged.</p>
<p>Users undertake to:</p>
<ul>
  <li>Use the site in accordance with its purpose and the laws in force in the Democratic Republic of Congo;</li>
  <li>Not disrupt the operation of the site or attempt unauthorised access to its systems;</li>
  <li>Provide accurate information in good faith when using the contact or reporting forms;</li>
  <li>Not use the reporting form for the purposes of slanderous accusation, defamation or harassment.</li>
</ul>
<p>Reports submitted through the platform are treated confidentially. Users may choose to report anonymously. The information provided is used exclusively within the framework of IGM's legal missions to combat mining fraud and smuggling.</p>
<p>IGM strives to ensure the accuracy and currency of the information published. However, content is provided for information purposes only and IGM cannot be held liable for any error, omission or temporary unavailability of the site. Only official texts published in the Official Gazette are authoritative.</p>
<p>The site may contain links to third-party websites, in particular partner institutions. IGM has no control over these sites and accepts no responsibility for their content.</p>
<p>IGM reserves the right to amend these terms and conditions at any time. The applicable terms are those in force on the date the site is consulted. These terms are governed by Congolese law; any dispute relating to their application falls under the jurisdiction of the courts of the Democratic Republic of Congo.</p>
<p>For any questions regarding these terms and conditions or the use of the site, you may contact the General Inspectorate of Mines via the contact page or the official contact details provided on the site.</p>
`.trim();

export const DEFAULT_TERMS_PAGE_FR: DefaultPageSeed = {
  routeKey: "terms",
  slug: "conditions-generales",
  title: "Conditions Générales",
  hero: {
    eyebrow: "Informations légales",
    title: "Conditions Générales",
    lead:
      "Modalités d'accès et d'utilisation du site officiel de l'Inspection Générale des Mines.",
    ctaLabel: "Nous contacter",
    ctaHref: "/contact",
  },
  contentHtml: TERMS_CONTENT_FR,
  seoTitle: "Conditions Générales — IGM",
  seoDescription:
    "Conditions générales d'utilisation du site officiel de l'Inspection Générale des Mines (IGM) en République Démocratique du Congo.",
};

export const DEFAULT_TERMS_PAGE_EN: DefaultPageSeed = {
  routeKey: "terms",
  slug: "terms-and-conditions",
  title: "Terms & conditions",
  hero: {
    eyebrow: "Legal information",
    title: "Terms & conditions",
    lead:
      "Terms of access and use of the official website of the General Inspectorate of Mines.",
    ctaLabel: "Contact us",
    ctaHref: "/contact",
  },
  contentHtml: TERMS_CONTENT_EN,
  seoTitle: "Terms & conditions — IGM",
  seoDescription:
    "Terms and conditions of use of the official website of the General Inspectorate of Mines (IGM) in the Democratic Republic of Congo.",
};

const COOKIES_CONTENT_FR = `
<p>La présente politique explique ce que sont les cookies, comment le site officiel de l'Inspection Générale des Mines (IGM) les utilise et comment vous pouvez les gérer.</p>
<p>Un cookie est un petit fichier texte déposé sur votre appareil (ordinateur, tablette, téléphone) lors de la consultation d'un site internet. Il permet notamment de mémoriser vos préférences de navigation et d'assurer le bon fonctionnement des services proposés.</p>
<p>Le site de l'IGM utilise un nombre limité de cookies, strictement nécessaires ou destinés à améliorer votre expérience :</p>
<ul>
  <li>Cookies techniques indispensables au fonctionnement du site, à la sécurité et à la navigation ;</li>
  <li>Cookie de préférence de langue, permettant de mémoriser votre choix entre le français et l'anglais ;</li>
  <li>Cookies de session liés à l'utilisation des formulaires du site, notamment le formulaire de signalement.</li>
</ul>
<p>Ces cookies ne sont pas utilisés à des fins publicitaires et ne servent pas à suivre votre navigation sur d'autres sites. Les informations qu'ils contiennent ne sont ni vendues ni communiquées à des tiers.</p>
<p>Les signalements effectués via la plateforme peuvent être réalisés de manière anonyme : les cookies utilisés par le site ne permettent pas d'identifier l'auteur d'un signalement anonyme.</p>
<p>Vous pouvez à tout moment gérer ou supprimer les cookies via les paramètres de votre navigateur :</p>
<ul>
  <li>Configurer votre navigateur pour accepter ou refuser les cookies, en totalité ou au cas par cas ;</li>
  <li>Supprimer les cookies déjà enregistrés sur votre appareil ;</li>
  <li>Activer la navigation privée, qui supprime automatiquement les cookies à la fermeture du navigateur.</li>
</ul>
<p>Le refus ou la suppression de certains cookies techniques peut toutefois altérer le fonctionnement de certaines fonctionnalités du site, notamment la mémorisation de la langue choisie.</p>
<p>La présente politique peut être mise à jour à tout moment, notamment en cas d'évolution du site ou de la réglementation applicable. La version en vigueur est celle publiée sur cette page.</p>
<p>Pour toute question relative à la présente politique des cookies, vous pouvez contacter l'Inspection Générale des Mines via la page contact du site.</p>
`.trim();

const COOKIES_CONTENT_EN = `
<p>This policy explains what cookies are, how the official website of the General Inspectorate of Mines (IGM) uses them and how you can manage them.</p>
<p>A cookie is a small text file placed on your device (computer, tablet, phone) when you visit a website. It is used in particular to remember your browsing preferences and to ensure the proper functioning of the services provided.</p>
<p>The IGM website uses a limited number of cookies, either strictly necessary or intended to improve your experience:</p>
<ul>
  <li>Technical cookies essential to the operation, security and navigation of the site;</li>
  <li>A language preference cookie, used to remember your choice between French and English;</li>
  <li>Session cookies related to the use of the site's forms, in particular the reporting form.</li>
</ul>
<p>These cookies are not used for advertising purposes and do not track your browsing on other websites. The information they contain is neither sold nor shared with third parties.</p>
<p>Reports submitted through the platform can be made anonymously: the cookies used by the site do not make it possible to identify the author of an anonymous report.</p>
<p>You can manage or delete cookies at any time through your browser settings:</p>
<ul>
  <li>Configure your browser to accept or refuse cookies, in full or on a case-by-case basis;</li>
  <li>Delete cookies already stored on your device;</li>
  <li>Enable private browsing, which automatically deletes cookies when the browser is closed.</li>
</ul>
<p>However, refusing or deleting certain technical cookies may affect the operation of some site features, in particular the storage of your language preference.</p>
<p>This policy may be updated at any time, in particular if the site or applicable regulations change. The version in force is the one published on this page.</p>
<p>For any questions regarding this cookie policy, you may contact the General Inspectorate of Mines via the site's contact page.</p>
`.trim();

export const DEFAULT_COOKIES_PAGE_FR: DefaultPageSeed = {
  routeKey: "cookies",
  slug: "politique-cookies",
  title: "Politiques des cookies",
  hero: {
    eyebrow: "Informations légales",
    title: "Politiques des cookies",
    lead:
      "Utilisation et gestion des cookies sur le site officiel de l'Inspection Générale des Mines.",
    ctaLabel: "Nous contacter",
    ctaHref: "/contact",
  },
  contentHtml: COOKIES_CONTENT_FR,
  seoTitle: "Politiques des cookies — IGM",
  seoDescription:
    "Politique des cookies du site officiel de l'Inspection Générale des Mines (IGM) : types de cookies utilisés, finalités et gestion par l'utilisateur.",
};

export const DEFAULT_COOKIES_PAGE_EN: DefaultPageSeed = {
  routeKey: "cookies",
  slug: "cookie-policy",
  title: "Cookie policy",
  hero: {
    eyebrow: "Legal information",
    title: "Cookie policy",
    lead:
      "Use and management of cookies on the official website of the General Inspectorate of Mines.",
    ctaLabel: "Contact us",
    ctaHref: "/contact",
  },
  contentHtml: COOKIES_CONTENT_EN,
  seoTitle: "Cookie policy — IGM",
  seoDescription:
    "Cookie policy of the official website of the General Inspectorate of Mines (IGM): types of cookies used, purposes and user management.",
};

const DEFAULT_PAGES_BY_LOCALE = {
  fr: [
    DEFAULT_MINING_FRAUD_PAGE_FR,
    DEFAULT_MINING_SMUGGLING_PAGE_FR,
    DEFAULT_SANCTIONS_PAGE_FR,
    DEFAULT_TERMS_PAGE_FR,
    DEFAULT_COOKIES_PAGE_FR,
  ],
  en: [
    DEFAULT_MINING_FRAUD_PAGE_EN,
    DEFAULT_MINING_SMUGGLING_PAGE_EN,
    DEFAULT_SANCTIONS_PAGE_EN,
    DEFAULT_TERMS_PAGE_EN,
    DEFAULT_COOKIES_PAGE_EN,
  ],
} satisfies Record<SupportedLocale, DefaultPageSeed[]>;

export function getDefaultPageSeed(slug: string, locale: SupportedLocale): DefaultPageSeed | null {
  const routeKey = findRouteKey(slug, locale);
  if (!routeKey) return null;

  return DEFAULT_PAGES_BY_LOCALE[locale].find((page) => page.routeKey === routeKey) ?? null;
}

export function defaultPageToCmsPage(seed: DefaultPageSeed): CmsPage {
  return {
    id: 0,
    slug: seed.slug,
    title: seed.title,
    summary: seed.summary ?? null,
    hero: seed.hero ?? undefined,
    contentHtml: seed.contentHtml,
    seoTitle: seed.seoTitle ?? null,
    seoDescription: seed.seoDescription ?? null,
  };
}

export function mergePageWithDefault(page: CmsPage | null, slug: string, locale: SupportedLocale): CmsPage | null {
  const fallback = getDefaultPageSeed(slug, locale);
  if (!fallback) return page;

  const base = defaultPageToCmsPage(fallback);

  if (!page) return base;

  const hasContent = Boolean(page.contentHtml?.trim() || page.summary?.trim());
  if (!hasContent) {
    return {
      ...page,
      title: page.title?.trim() || base.title,
      summary: page.summary?.trim() || base.summary,
      hero: page.hero?.title?.trim() ? page.hero : base.hero,
      contentHtml: base.contentHtml,
      seoTitle: page.seoTitle?.trim() || base.seoTitle,
      seoDescription: page.seoDescription?.trim() || base.seoDescription,
    };
  }

  return page;
}

export const DEFAULT_PAGE_SEED_PAIRS = [
  { fr: DEFAULT_MINING_FRAUD_PAGE_FR, en: DEFAULT_MINING_FRAUD_PAGE_EN },
  { fr: DEFAULT_MINING_SMUGGLING_PAGE_FR, en: DEFAULT_MINING_SMUGGLING_PAGE_EN },
  { fr: DEFAULT_SANCTIONS_PAGE_FR, en: DEFAULT_SANCTIONS_PAGE_EN },
  { fr: DEFAULT_TERMS_PAGE_FR, en: DEFAULT_TERMS_PAGE_EN },
  { fr: DEFAULT_COOKIES_PAGE_FR, en: DEFAULT_COOKIES_PAGE_EN },
] as const;
