/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  jsonb,
  boolean,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum__locales = pgEnum("enum__locales", ["fr", "en"]);
export const enum_pages_status = pgEnum("enum_pages_status", [
  "draft",
  "published",
]);
export const enum__pages_v_version_status = pgEnum(
  "enum__pages_v_version_status",
  ["draft", "published"],
);
export const enum__pages_v_published_locale = pgEnum(
  "enum__pages_v_published_locale",
  ["fr", "en"],
);
export const enum_news_status = pgEnum("enum_news_status", [
  "draft",
  "published",
]);
export const enum__news_v_version_status = pgEnum(
  "enum__news_v_version_status",
  ["draft", "published"],
);
export const enum__news_v_published_locale = pgEnum(
  "enum__news_v_published_locale",
  ["fr", "en"],
);
export const enum_signalements_status = pgEnum("enum_signalements_status", [
  "recu",
  "en_cours",
  "traite",
  "cloture",
]);
export const enum_signalements_province = pgEnum("enum_signalements_province", [
  "Bas-Uele",
  "Équateur",
  "Haut-Katanga",
  "Haut-Lomami",
  "Haut-Uele",
  "Ituri",
  "Kasaï",
  "Kasaï-Central",
  "Kasaï-Oriental",
  "Kinshasa",
  "Kongo-Central",
  "Kwango",
  "Kwilu",
  "Lomami",
  "Lualaba",
  "Mai-Ndombe",
  "Maniema",
  "Mongala",
  "Nord-Kivu",
  "Nord-Ubangi",
  "Sankuru",
  "Sud-Kivu",
  "Sud-Ubangi",
  "Tanganyika",
  "Tshopo",
  "Tshuapa",
]);
export const enum_signalements_type_infraction = pgEnum(
  "enum_signalements_type_infraction",
  [
    "Exploitation illégale",
    "Contrebande",
    "Sous-déclaration",
    "Corruption",
    "Non-respect des obligations légales",
    "Autre",
  ],
);
export const enum_site_settings_header_nav_children_sub_items_item_type =
  pgEnum("enum_site_settings_header_nav_children_sub_items_item_type", [
    "link",
    "dropdown",
    "report",
  ]);
export const enum_site_settings_header_nav_children_sub_items_nav_link = pgEnum(
  "enum_site_settings_header_nav_children_sub_items_nav_link",
  [
    "/",
    "/a-propos",
    "/historique",
    "/mission",
    "/vision",
    "/organigramme",
    "/cartographie",
    "/fraude-miniere",
    "/contrebande-miniere",
    "/denoncer",
    "/sanctions",
    "/actualites",
    "/ordonnances",
    "/lois",
    "/decrets",
    "/decisions",
    "/photos",
    "/videos",
    "/audios",
    "/contact",
    "__custom__",
  ],
);
export const enum_site_settings_header_nav_children_sub_items_nested_icon =
  pgEnum("enum_site_settings_header_nav_children_sub_items_nested_icon", [
    "plus",
    "caret",
  ]);
export const enum_site_settings_header_nav_children_item_type = pgEnum(
  "enum_site_settings_header_nav_children_item_type",
  ["link", "dropdown", "report"],
);
export const enum_site_settings_header_nav_children_nav_link = pgEnum(
  "enum_site_settings_header_nav_children_nav_link",
  [
    "/",
    "/a-propos",
    "/historique",
    "/mission",
    "/vision",
    "/organigramme",
    "/cartographie",
    "/fraude-miniere",
    "/contrebande-miniere",
    "/denoncer",
    "/sanctions",
    "/actualites",
    "/ordonnances",
    "/lois",
    "/decrets",
    "/decisions",
    "/photos",
    "/videos",
    "/audios",
    "/contact",
    "__custom__",
  ],
);
export const enum_site_settings_header_nav_children_nested_icon = pgEnum(
  "enum_site_settings_header_nav_children_nested_icon",
  ["plus", "caret"],
);
export const enum_site_settings_header_nav_item_type = pgEnum(
  "enum_site_settings_header_nav_item_type",
  ["link", "dropdown", "report"],
);
export const enum_site_settings_header_nav_nav_link = pgEnum(
  "enum_site_settings_header_nav_nav_link",
  [
    "/",
    "/a-propos",
    "/historique",
    "/mission",
    "/vision",
    "/organigramme",
    "/cartographie",
    "/fraude-miniere",
    "/contrebande-miniere",
    "/denoncer",
    "/sanctions",
    "/actualites",
    "/ordonnances",
    "/lois",
    "/decrets",
    "/decisions",
    "/photos",
    "/videos",
    "/audios",
    "/contact",
    "__custom__",
  ],
);
export const enum_site_settings_header_nav_nested_icon = pgEnum(
  "enum_site_settings_header_nav_nested_icon",
  ["plus", "caret"],
);
export const enum_site_settings_footer_columns_links_nav_link = pgEnum(
  "enum_site_settings_footer_columns_links_nav_link",
  [
    "/",
    "/a-propos",
    "/historique",
    "/mission",
    "/vision",
    "/organigramme",
    "/cartographie",
    "/fraude-miniere",
    "/contrebande-miniere",
    "/denoncer",
    "/sanctions",
    "/actualites",
    "/ordonnances",
    "/lois",
    "/decrets",
    "/decisions",
    "/photos",
    "/videos",
    "/audios",
    "/contact",
    "__custom__",
  ],
);
export const enum_site_settings_footer_social_network = pgEnum(
  "enum_site_settings_footer_social_network",
  ["facebook", "linkedin", "youtube", "instagram", "x"],
);
export const enum_site_settings_footer_legal_links_nav_link = pgEnum(
  "enum_site_settings_footer_legal_links_nav_link",
  [
    "/",
    "/a-propos",
    "/historique",
    "/mission",
    "/vision",
    "/organigramme",
    "/cartographie",
    "/fraude-miniere",
    "/contrebande-miniere",
    "/denoncer",
    "/sanctions",
    "/actualites",
    "/ordonnances",
    "/lois",
    "/decrets",
    "/decisions",
    "/photos",
    "/videos",
    "/audios",
    "/contact",
    "__custom__",
  ],
);
export const enum_home_banner_slides_slide_type = pgEnum(
  "enum_home_banner_slides_slide_type",
  ["image", "video"],
);
export const enum_home_banner_slides_primary_cta_nav_link = pgEnum(
  "enum_home_banner_slides_primary_cta_nav_link",
  [
    "/",
    "/a-propos",
    "/historique",
    "/mission",
    "/vision",
    "/organigramme",
    "/cartographie",
    "/fraude-miniere",
    "/contrebande-miniere",
    "/denoncer",
    "/sanctions",
    "/actualites",
    "/ordonnances",
    "/lois",
    "/decrets",
    "/decisions",
    "/photos",
    "/videos",
    "/audios",
    "/contact",
    "__custom__",
  ],
);
export const enum_home_banner_slides_secondary_cta_nav_link = pgEnum(
  "enum_home_banner_slides_secondary_cta_nav_link",
  [
    "/",
    "/a-propos",
    "/historique",
    "/mission",
    "/vision",
    "/organigramme",
    "/cartographie",
    "/fraude-miniere",
    "/contrebande-miniere",
    "/denoncer",
    "/sanctions",
    "/actualites",
    "/ordonnances",
    "/lois",
    "/decrets",
    "/decisions",
    "/photos",
    "/videos",
    "/audios",
    "/contact",
    "__custom__",
  ],
);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt").notNull(),
    prefix: varchar("prefix").default("public"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
  ],
);

export const signalement_files = pgTable(
  "signalement_files",
  {
    id: serial("id").primaryKey(),
    prefix: varchar("prefix").default("private/signalements"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
  },
  (columns) => [
    index("signalement_files_updated_at_idx").on(columns.updatedAt),
    index("signalement_files_created_at_idx").on(columns.createdAt),
    uniqueIndex("signalement_files_filename_idx").on(columns.filename),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    hero_media: integer("hero_media_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status("_status").default("draft"),
  },
  (columns) => [
    index("pages_hero_hero_media_idx").on(columns.hero_media),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
    index("pages__status_idx").on(columns._status),
  ],
);

export const pages_locales = pgTable(
  "pages_locales",
  {
    title: varchar("title"),
    slug: varchar("slug"),
    summary: varchar("summary"),
    hero_eyebrow: varchar("hero_eyebrow"),
    hero_title: varchar("hero_title"),
    hero_lead: varchar("hero_lead"),
    hero_ctaLabel: varchar("hero_cta_label"),
    hero_ctaHref: varchar("hero_cta_href"),
    content: jsonb("content"),
    contentHtml: varchar("content_html"),
    seoTitle: varchar("seo_title"),
    seoDescription: varchar("seo_description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("pages_slug_idx").on(columns.slug, columns._locale),
    uniqueIndex("pages_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v = pgTable(
  "_pages_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    version_hero_media: integer("version_hero_media_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__pages_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__pages_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_pages_v_parent_idx").on(columns.parent),
    index("_pages_v_version_hero_version_hero_media_idx").on(
      columns.version_hero_media,
    ),
    index("_pages_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_pages_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_pages_v_version_version__status_idx").on(columns.version__status),
    index("_pages_v_created_at_idx").on(columns.createdAt),
    index("_pages_v_updated_at_idx").on(columns.updatedAt),
    index("_pages_v_snapshot_idx").on(columns.snapshot),
    index("_pages_v_published_locale_idx").on(columns.publishedLocale),
    index("_pages_v_latest_idx").on(columns.latest),
  ],
);

export const _pages_v_locales = pgTable(
  "_pages_v_locales",
  {
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_summary: varchar("version_summary"),
    version_hero_eyebrow: varchar("version_hero_eyebrow"),
    version_hero_title: varchar("version_hero_title"),
    version_hero_lead: varchar("version_hero_lead"),
    version_hero_ctaLabel: varchar("version_hero_cta_label"),
    version_hero_ctaHref: varchar("version_hero_cta_href"),
    version_content: jsonb("version_content"),
    version_contentHtml: varchar("version_content_html"),
    version_seoTitle: varchar("version_seo_title"),
    version_seoDescription: varchar("version_seo_description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    index("_pages_v_version_version_slug_idx").on(
      columns.version_slug,
      columns._locale,
    ),
    uniqueIndex("_pages_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const news = pgTable(
  "news",
  {
    id: serial("id").primaryKey(),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    cover: integer("cover_id").references(() => media.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_news_status("_status").default("draft"),
  },
  (columns) => [
    index("news_cover_idx").on(columns.cover),
    index("news_updated_at_idx").on(columns.updatedAt),
    index("news_created_at_idx").on(columns.createdAt),
    index("news__status_idx").on(columns._status),
  ],
);

export const news_locales = pgTable(
  "news_locales",
  {
    title: varchar("title"),
    slug: varchar("slug"),
    excerpt: varchar("excerpt"),
    category: varchar("category"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("news_slug_idx").on(columns.slug, columns._locale),
    uniqueIndex("news_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [news.id],
      name: "news_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _news_v = pgTable(
  "_news_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => news.id, {
      onDelete: "set null",
    }),
    version_publishedAt: timestamp("version_published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_cover: integer("version_cover_id").references(() => media.id, {
      onDelete: "set null",
    }),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__news_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__news_v_published_locale("published_locale"),
    latest: boolean("latest"),
  },
  (columns) => [
    index("_news_v_parent_idx").on(columns.parent),
    index("_news_v_version_version_cover_idx").on(columns.version_cover),
    index("_news_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_news_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_news_v_version_version__status_idx").on(columns.version__status),
    index("_news_v_created_at_idx").on(columns.createdAt),
    index("_news_v_updated_at_idx").on(columns.updatedAt),
    index("_news_v_snapshot_idx").on(columns.snapshot),
    index("_news_v_published_locale_idx").on(columns.publishedLocale),
    index("_news_v_latest_idx").on(columns.latest),
  ],
);

export const _news_v_locales = pgTable(
  "_news_v_locales",
  {
    version_title: varchar("version_title"),
    version_slug: varchar("version_slug"),
    version_excerpt: varchar("version_excerpt"),
    version_category: varchar("version_category"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    index("_news_v_version_version_slug_idx").on(
      columns.version_slug,
      columns._locale,
    ),
    uniqueIndex("_news_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_news_v.id],
      name: "_news_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const stats = pgTable(
  "stats",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    value: numeric("value", { mode: "number" }).notNull(),
    order: numeric("order", { mode: "number" }).default(0),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("stats_key_idx").on(columns.key),
    index("stats_updated_at_idx").on(columns.updatedAt),
    index("stats_created_at_idx").on(columns.createdAt),
  ],
);

export const stats_locales = pgTable(
  "stats_locales",
  {
    label: varchar("label").notNull(),
    suffix: varchar("suffix"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("stats_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [stats.id],
      name: "stats_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const signalements = pgTable(
  "signalements",
  {
    id: serial("id").primaryKey(),
    status: enum_signalements_status("status").default("recu"),
    alerteur_nom: varchar("alerteur_nom"),
    alerteur_email: varchar("alerteur_email"),
    alerteur_tel: varchar("alerteur_tel"),
    description: varchar("description").notNull(),
    province: enum_signalements_province("province"),
    villeSite: varchar("ville_site"),
    coords: varchar("coords"),
    typeInfraction: enum_signalements_type_infraction("type_infraction"),
    notesInternes: varchar("notes_internes"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("signalements_updated_at_idx").on(columns.updatedAt),
    index("signalements_created_at_idx").on(columns.createdAt),
  ],
);

export const signalements_rels = pgTable(
  "signalements_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    "signalement-filesID": integer("signalement_files_id"),
  },
  (columns) => [
    index("signalements_rels_order_idx").on(columns.order),
    index("signalements_rels_parent_idx").on(columns.parent),
    index("signalements_rels_path_idx").on(columns.path),
    index("signalements_rels_signalement_files_id_idx").on(
      columns["signalement-filesID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [signalements.id],
      name: "signalements_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["signalement-filesID"]],
      foreignColumns: [signalement_files.id],
      name: "signalements_rels_signalement_files_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    mediaID: integer("media_id"),
    "signalement-filesID": integer("signalement_files_id"),
    pagesID: integer("pages_id"),
    newsID: integer("news_id"),
    statsID: integer("stats_id"),
    signalementsID: integer("signalements_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_signalement_files_id_idx").on(
      columns["signalement-filesID"],
    ),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_news_id_idx").on(columns.newsID),
    index("payload_locked_documents_rels_stats_id_idx").on(columns.statsID),
    index("payload_locked_documents_rels_signalements_id_idx").on(
      columns.signalementsID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["signalement-filesID"]],
      foreignColumns: [signalement_files.id],
      name: "payload_locked_documents_rels_signalement_files_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["newsID"]],
      foreignColumns: [news.id],
      name: "payload_locked_documents_rels_news_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["statsID"]],
      foreignColumns: [stats.id],
      name: "payload_locked_documents_rels_stats_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["signalementsID"]],
      foreignColumns: [signalements.id],
      name: "payload_locked_documents_rels_signalements_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const site_settings_header_nav_children_sub_items = pgTable(
  "site_settings_header_nav_children_sub_items",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    itemType:
      enum_site_settings_header_nav_children_sub_items_item_type(
        "item_type",
      ).default("link"),
    navLink:
      enum_site_settings_header_nav_children_sub_items_nav_link("nav_link"),
    customHref: varchar("custom_href"),
    cssClass: varchar("css_class"),
    nestedIcon:
      enum_site_settings_header_nav_children_sub_items_nested_icon(
        "nested_icon",
      ).default("plus"),
  },
  (columns) => [
    index("site_settings_header_nav_children_sub_items_order_idx").on(
      columns._order,
    ),
    index("site_settings_header_nav_children_sub_items_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings_header_nav_children.id],
      name: "site_settings_header_nav_children_sub_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_header_nav_children_sub_items_locales = pgTable(
  "site_settings_header_nav_children_sub_items_locales",
  {
    label: varchar("label"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "site_settings_header_nav_children_sub_items_locales_locale_p",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings_header_nav_children_sub_items.id],
      name: "site_settings_header_nav_children_sub_items_locales_paren_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_header_nav_children = pgTable(
  "site_settings_header_nav_children",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    itemType:
      enum_site_settings_header_nav_children_item_type("item_type").default(
        "link",
      ),
    navLink: enum_site_settings_header_nav_children_nav_link("nav_link"),
    customHref: varchar("custom_href"),
    cssClass: varchar("css_class"),
    nestedIcon:
      enum_site_settings_header_nav_children_nested_icon("nested_icon").default(
        "plus",
      ),
  },
  (columns) => [
    index("site_settings_header_nav_children_order_idx").on(columns._order),
    index("site_settings_header_nav_children_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings_header_nav.id],
      name: "site_settings_header_nav_children_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_header_nav_children_locales = pgTable(
  "site_settings_header_nav_children_locales",
  {
    label: varchar("label"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "site_settings_header_nav_children_locales_locale_parent_id_u",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings_header_nav_children.id],
      name: "site_settings_header_nav_children_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_header_nav = pgTable(
  "site_settings_header_nav",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    itemType: enum_site_settings_header_nav_item_type("item_type")
      .notNull()
      .default("link"),
    navLink: enum_site_settings_header_nav_nav_link("nav_link"),
    customHref: varchar("custom_href"),
    cssClass: varchar("css_class"),
    nestedIcon:
      enum_site_settings_header_nav_nested_icon("nested_icon").default("plus"),
  },
  (columns) => [
    index("site_settings_header_nav_order_idx").on(columns._order),
    index("site_settings_header_nav_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_header_nav_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_header_nav_locales = pgTable(
  "site_settings_header_nav_locales",
  {
    label: varchar("label").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("site_settings_header_nav_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings_header_nav.id],
      name: "site_settings_header_nav_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_footer_columns_links = pgTable(
  "site_settings_footer_columns_links",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    navLink: enum_site_settings_footer_columns_links_nav_link("nav_link"),
    customHref: varchar("custom_href"),
    openInNewTab: boolean("open_in_new_tab").default(false),
  },
  (columns) => [
    index("site_settings_footer_columns_links_order_idx").on(columns._order),
    index("site_settings_footer_columns_links_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings_footer_columns.id],
      name: "site_settings_footer_columns_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_footer_columns_links_locales = pgTable(
  "site_settings_footer_columns_links_locales",
  {
    label: varchar("label").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "site_settings_footer_columns_links_locales_locale_parent_id_",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings_footer_columns_links.id],
      name: "site_settings_footer_columns_links_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_footer_columns = pgTable(
  "site_settings_footer_columns",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
  },
  (columns) => [
    index("site_settings_footer_columns_order_idx").on(columns._order),
    index("site_settings_footer_columns_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_footer_columns_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_footer_columns_locales = pgTable(
  "site_settings_footer_columns_locales",
  {
    title: varchar("title").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "site_settings_footer_columns_locales_locale_parent_id_unique",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings_footer_columns.id],
      name: "site_settings_footer_columns_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_footer_social = pgTable(
  "site_settings_footer_social",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    network: enum_site_settings_footer_social_network("network").notNull(),
    url: varchar("url").notNull(),
  },
  (columns) => [
    index("site_settings_footer_social_order_idx").on(columns._order),
    index("site_settings_footer_social_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_footer_social_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_footer_legal_links = pgTable(
  "site_settings_footer_legal_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    navLink: enum_site_settings_footer_legal_links_nav_link("nav_link"),
    customHref: varchar("custom_href"),
    openInNewTab: boolean("open_in_new_tab").default(false),
  },
  (columns) => [
    index("site_settings_footer_legal_links_order_idx").on(columns._order),
    index("site_settings_footer_legal_links_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_footer_legal_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings_footer_legal_links_locales = pgTable(
  "site_settings_footer_legal_links_locales",
  {
    label: varchar("label").notNull(),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "site_settings_footer_legal_links_locales_locale_parent_id_un",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings_footer_legal_links.id],
      name: "site_settings_footer_legal_links_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const site_settings = pgTable(
  "site_settings",
  {
    id: serial("id").primaryKey(),
    phoneVert: varchar("phone_vert").default("+243 97 684 4563"),
    email: varchar("email").default("info@igm.cd"),
    logo: integer("logo_id").references(() => media.id, {
      onDelete: "set null",
    }),
    footerContactPhone: varchar("footer_contact_phone").default(
      "+243 900 030 005",
    ),
    footerContactEmail: varchar("footer_contact_email"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [index("site_settings_logo_idx").on(columns.logo)],
);

export const site_settings_locales = pgTable(
  "site_settings_locales",
  {
    siteName: varchar("site_name").notNull().default("IGM"),
    address: varchar("address"),
    footerHqHeading: varchar("footer_hq_heading").default("Adresse du siège"),
    footerHqText: varchar("footer_hq_text"),
    footerContactTitle: varchar("footer_contact_title").default("Contact"),
    footerContactLead: varchar("footer_contact_lead"),
    footerSocialTitle: varchar("footer_social_title").default(
      "Réseaux sociaux",
    ),
    footerCopyright: varchar("footer_copyright"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("site_settings_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [site_settings.id],
      name: "site_settings_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const home_banner_slides_features = pgTable(
  "home_banner_slides_features",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
  },
  (columns) => [
    index("home_banner_slides_features_order_idx").on(columns._order),
    index("home_banner_slides_features_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home_banner_slides.id],
      name: "home_banner_slides_features_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const home_banner_slides_features_locales = pgTable(
  "home_banner_slides_features_locales",
  {
    label: varchar("label"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex(
      "home_banner_slides_features_locales_locale_parent_id_unique",
    ).on(columns._locale, columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home_banner_slides_features.id],
      name: "home_banner_slides_features_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const home_banner_slides = pgTable(
  "home_banner_slides",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    adminLabel: varchar("admin_label"),
    slideType:
      enum_home_banner_slides_slide_type("slide_type").default("image"),
    image: integer("image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    video: integer("video_id").references(() => media.id, {
      onDelete: "set null",
    }),
    primaryCta_navLink: enum_home_banner_slides_primary_cta_nav_link(
      "primary_cta_nav_link",
    ),
    primaryCta_customHref: varchar("primary_cta_custom_href"),
    secondaryCta_navLink: enum_home_banner_slides_secondary_cta_nav_link(
      "secondary_cta_nav_link",
    ),
    secondaryCta_customHref: varchar("secondary_cta_custom_href"),
  },
  (columns) => [
    index("home_banner_slides_order_idx").on(columns._order),
    index("home_banner_slides_parent_id_idx").on(columns._parentID),
    index("home_banner_slides_image_idx").on(columns.image),
    index("home_banner_slides_video_idx").on(columns.video),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_banner_slides_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const home_banner_slides_locales = pgTable(
  "home_banner_slides_locales",
  {
    badge: varchar("badge"),
    title: varchar("title").notNull(),
    lead: varchar("lead"),
    primaryCta_label: varchar("primary_cta_label"),
    secondaryCta_label: varchar("secondary_cta_label"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("home_banner_slides_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home_banner_slides.id],
      name: "home_banner_slides_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const home_strategy_axes = pgTable(
  "home_strategy_axes",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
  },
  (columns) => [
    index("home_strategy_axes_order_idx").on(columns._order),
    index("home_strategy_axes_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_strategy_axes_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const home_strategy_axes_locales = pgTable(
  "home_strategy_axes_locales",
  {
    highlight: varchar("highlight"),
    text: varchar("text"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: varchar("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("home_strategy_axes_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home_strategy_axes.id],
      name: "home_strategy_axes_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const home = pgTable(
  "home",
  {
    id: serial("id").primaryKey(),
    about_image: integer("about_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    newsSection_maxItems: numeric("news_section_max_items", {
      mode: "number",
    }).default(6),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [index("home_about_about_image_idx").on(columns.about_image)],
);

export const home_locales = pgTable(
  "home_locales",
  {
    seoTitle: varchar("seo_title").default(
      "IGM — Inspection Générale des Mines",
    ),
    seoDescription: varchar("seo_description"),
    about_title: varchar("about_title"),
    about_mission_title: varchar("about_mission_title").default(
      "Notre Mission",
    ),
    about_mission_text: varchar("about_mission_text"),
    about_mission_href: varchar("about_mission_href").default("/mission"),
    about_vision_title: varchar("about_vision_title").default("Notre Vision"),
    about_vision_text: varchar("about_vision_text"),
    about_vision_href: varchar("about_vision_href").default("/vision"),
    about_leadText: varchar("about_lead_text"),
    about_detailText: varchar("about_detail_text"),
    about_signatureName: varchar("about_signature_name"),
    about_signatureRole: varchar("about_signature_role"),
    strategy_title: varchar("strategy_title"),
    strategy_lead: varchar("strategy_lead"),
    strategy_axesTitle: varchar("strategy_axes_title").default(
      "Axes Stratégiques :",
    ),
    strategy_counterLabel: varchar("strategy_counter_label").default(
      "Provinces de présence.",
    ),
    strategy_ctaLabel: varchar("strategy_cta_label"),
    strategy_ctaHref: varchar("strategy_cta_href").default("/contact"),
    statsSection_title: varchar("stats_section_title"),
    statsSection_lead: varchar("stats_section_lead"),
    newsSection_title: varchar("news_section_title").default(
      "Dernières actualités.",
    ),
    newsSection_lead: varchar("news_section_lead"),
    contactSection_title: varchar("contact_section_title"),
    contactSection_lead: varchar("contact_section_lead"),
    contactSection_buttonLabel: varchar("contact_section_button_label").default(
      "Dénoncer",
    ),
    contactSection_buttonHref: varchar("contact_section_button_href").default(
      "/denoncer",
    ),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    uniqueIndex("home_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [home.id],
      name: "home_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_media = relations(media, () => ({}));
export const relations_signalement_files = relations(
  signalement_files,
  () => ({}),
);
export const relations_pages_locales = relations(pages_locales, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_locales._parentID],
    references: [pages.id],
    relationName: "_locales",
  }),
}));
export const relations_pages = relations(pages, ({ one, many }) => ({
  hero_media: one(media, {
    fields: [pages.hero_media],
    references: [media.id],
    relationName: "hero_media",
  }),
  _locales: many(pages_locales, {
    relationName: "_locales",
  }),
}));
export const relations__pages_v_locales = relations(
  _pages_v_locales,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_locales._parentID],
      references: [_pages_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: "parent",
  }),
  version_hero_media: one(media, {
    fields: [_pages_v.version_hero_media],
    references: [media.id],
    relationName: "version_hero_media",
  }),
  _locales: many(_pages_v_locales, {
    relationName: "_locales",
  }),
}));
export const relations_news_locales = relations(news_locales, ({ one }) => ({
  _parentID: one(news, {
    fields: [news_locales._parentID],
    references: [news.id],
    relationName: "_locales",
  }),
}));
export const relations_news = relations(news, ({ one, many }) => ({
  cover: one(media, {
    fields: [news.cover],
    references: [media.id],
    relationName: "cover",
  }),
  _locales: many(news_locales, {
    relationName: "_locales",
  }),
}));
export const relations__news_v_locales = relations(
  _news_v_locales,
  ({ one }) => ({
    _parentID: one(_news_v, {
      fields: [_news_v_locales._parentID],
      references: [_news_v.id],
      relationName: "_locales",
    }),
  }),
);
export const relations__news_v = relations(_news_v, ({ one, many }) => ({
  parent: one(news, {
    fields: [_news_v.parent],
    references: [news.id],
    relationName: "parent",
  }),
  version_cover: one(media, {
    fields: [_news_v.version_cover],
    references: [media.id],
    relationName: "version_cover",
  }),
  _locales: many(_news_v_locales, {
    relationName: "_locales",
  }),
}));
export const relations_stats_locales = relations(stats_locales, ({ one }) => ({
  _parentID: one(stats, {
    fields: [stats_locales._parentID],
    references: [stats.id],
    relationName: "_locales",
  }),
}));
export const relations_stats = relations(stats, ({ many }) => ({
  _locales: many(stats_locales, {
    relationName: "_locales",
  }),
}));
export const relations_signalements_rels = relations(
  signalements_rels,
  ({ one }) => ({
    parent: one(signalements, {
      fields: [signalements_rels.parent],
      references: [signalements.id],
      relationName: "_rels",
    }),
    "signalement-filesID": one(signalement_files, {
      fields: [signalements_rels["signalement-filesID"]],
      references: [signalement_files.id],
      relationName: "signalement-files",
    }),
  }),
);
export const relations_signalements = relations(signalements, ({ many }) => ({
  _rels: many(signalements_rels, {
    relationName: "_rels",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    "signalement-filesID": one(signalement_files, {
      fields: [payload_locked_documents_rels["signalement-filesID"]],
      references: [signalement_files.id],
      relationName: "signalement-files",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    newsID: one(news, {
      fields: [payload_locked_documents_rels.newsID],
      references: [news.id],
      relationName: "news",
    }),
    statsID: one(stats, {
      fields: [payload_locked_documents_rels.statsID],
      references: [stats.id],
      relationName: "stats",
    }),
    signalementsID: one(signalements, {
      fields: [payload_locked_documents_rels.signalementsID],
      references: [signalements.id],
      relationName: "signalements",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_site_settings_header_nav_children_sub_items_locales =
  relations(site_settings_header_nav_children_sub_items_locales, ({ one }) => ({
    _parentID: one(site_settings_header_nav_children_sub_items, {
      fields: [site_settings_header_nav_children_sub_items_locales._parentID],
      references: [site_settings_header_nav_children_sub_items.id],
      relationName: "_locales",
    }),
  }));
export const relations_site_settings_header_nav_children_sub_items = relations(
  site_settings_header_nav_children_sub_items,
  ({ one, many }) => ({
    _parentID: one(site_settings_header_nav_children, {
      fields: [site_settings_header_nav_children_sub_items._parentID],
      references: [site_settings_header_nav_children.id],
      relationName: "subItems",
    }),
    _locales: many(site_settings_header_nav_children_sub_items_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_site_settings_header_nav_children_locales = relations(
  site_settings_header_nav_children_locales,
  ({ one }) => ({
    _parentID: one(site_settings_header_nav_children, {
      fields: [site_settings_header_nav_children_locales._parentID],
      references: [site_settings_header_nav_children.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_site_settings_header_nav_children = relations(
  site_settings_header_nav_children,
  ({ one, many }) => ({
    _parentID: one(site_settings_header_nav, {
      fields: [site_settings_header_nav_children._parentID],
      references: [site_settings_header_nav.id],
      relationName: "children",
    }),
    _locales: many(site_settings_header_nav_children_locales, {
      relationName: "_locales",
    }),
    subItems: many(site_settings_header_nav_children_sub_items, {
      relationName: "subItems",
    }),
  }),
);
export const relations_site_settings_header_nav_locales = relations(
  site_settings_header_nav_locales,
  ({ one }) => ({
    _parentID: one(site_settings_header_nav, {
      fields: [site_settings_header_nav_locales._parentID],
      references: [site_settings_header_nav.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_site_settings_header_nav = relations(
  site_settings_header_nav,
  ({ one, many }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_header_nav._parentID],
      references: [site_settings.id],
      relationName: "headerNav",
    }),
    _locales: many(site_settings_header_nav_locales, {
      relationName: "_locales",
    }),
    children: many(site_settings_header_nav_children, {
      relationName: "children",
    }),
  }),
);
export const relations_site_settings_footer_columns_links_locales = relations(
  site_settings_footer_columns_links_locales,
  ({ one }) => ({
    _parentID: one(site_settings_footer_columns_links, {
      fields: [site_settings_footer_columns_links_locales._parentID],
      references: [site_settings_footer_columns_links.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_site_settings_footer_columns_links = relations(
  site_settings_footer_columns_links,
  ({ one, many }) => ({
    _parentID: one(site_settings_footer_columns, {
      fields: [site_settings_footer_columns_links._parentID],
      references: [site_settings_footer_columns.id],
      relationName: "links",
    }),
    _locales: many(site_settings_footer_columns_links_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_site_settings_footer_columns_locales = relations(
  site_settings_footer_columns_locales,
  ({ one }) => ({
    _parentID: one(site_settings_footer_columns, {
      fields: [site_settings_footer_columns_locales._parentID],
      references: [site_settings_footer_columns.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_site_settings_footer_columns = relations(
  site_settings_footer_columns,
  ({ one, many }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_footer_columns._parentID],
      references: [site_settings.id],
      relationName: "footerColumns",
    }),
    _locales: many(site_settings_footer_columns_locales, {
      relationName: "_locales",
    }),
    links: many(site_settings_footer_columns_links, {
      relationName: "links",
    }),
  }),
);
export const relations_site_settings_footer_social = relations(
  site_settings_footer_social,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_footer_social._parentID],
      references: [site_settings.id],
      relationName: "footerSocial",
    }),
  }),
);
export const relations_site_settings_footer_legal_links_locales = relations(
  site_settings_footer_legal_links_locales,
  ({ one }) => ({
    _parentID: one(site_settings_footer_legal_links, {
      fields: [site_settings_footer_legal_links_locales._parentID],
      references: [site_settings_footer_legal_links.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_site_settings_footer_legal_links = relations(
  site_settings_footer_legal_links,
  ({ one, many }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_footer_legal_links._parentID],
      references: [site_settings.id],
      relationName: "footerLegalLinks",
    }),
    _locales: many(site_settings_footer_legal_links_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_site_settings_locales = relations(
  site_settings_locales,
  ({ one }) => ({
    _parentID: one(site_settings, {
      fields: [site_settings_locales._parentID],
      references: [site_settings.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_site_settings = relations(
  site_settings,
  ({ one, many }) => ({
    logo: one(media, {
      fields: [site_settings.logo],
      references: [media.id],
      relationName: "logo",
    }),
    headerNav: many(site_settings_header_nav, {
      relationName: "headerNav",
    }),
    footerColumns: many(site_settings_footer_columns, {
      relationName: "footerColumns",
    }),
    footerSocial: many(site_settings_footer_social, {
      relationName: "footerSocial",
    }),
    footerLegalLinks: many(site_settings_footer_legal_links, {
      relationName: "footerLegalLinks",
    }),
    _locales: many(site_settings_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_home_banner_slides_features_locales = relations(
  home_banner_slides_features_locales,
  ({ one }) => ({
    _parentID: one(home_banner_slides_features, {
      fields: [home_banner_slides_features_locales._parentID],
      references: [home_banner_slides_features.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_home_banner_slides_features = relations(
  home_banner_slides_features,
  ({ one, many }) => ({
    _parentID: one(home_banner_slides, {
      fields: [home_banner_slides_features._parentID],
      references: [home_banner_slides.id],
      relationName: "features",
    }),
    _locales: many(home_banner_slides_features_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_home_banner_slides_locales = relations(
  home_banner_slides_locales,
  ({ one }) => ({
    _parentID: one(home_banner_slides, {
      fields: [home_banner_slides_locales._parentID],
      references: [home_banner_slides.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_home_banner_slides = relations(
  home_banner_slides,
  ({ one, many }) => ({
    _parentID: one(home, {
      fields: [home_banner_slides._parentID],
      references: [home.id],
      relationName: "bannerSlides",
    }),
    _locales: many(home_banner_slides_locales, {
      relationName: "_locales",
    }),
    image: one(media, {
      fields: [home_banner_slides.image],
      references: [media.id],
      relationName: "image",
    }),
    video: one(media, {
      fields: [home_banner_slides.video],
      references: [media.id],
      relationName: "video",
    }),
    features: many(home_banner_slides_features, {
      relationName: "features",
    }),
  }),
);
export const relations_home_strategy_axes_locales = relations(
  home_strategy_axes_locales,
  ({ one }) => ({
    _parentID: one(home_strategy_axes, {
      fields: [home_strategy_axes_locales._parentID],
      references: [home_strategy_axes.id],
      relationName: "_locales",
    }),
  }),
);
export const relations_home_strategy_axes = relations(
  home_strategy_axes,
  ({ one, many }) => ({
    _parentID: one(home, {
      fields: [home_strategy_axes._parentID],
      references: [home.id],
      relationName: "strategy_axes",
    }),
    _locales: many(home_strategy_axes_locales, {
      relationName: "_locales",
    }),
  }),
);
export const relations_home_locales = relations(home_locales, ({ one }) => ({
  _parentID: one(home, {
    fields: [home_locales._parentID],
    references: [home.id],
    relationName: "_locales",
  }),
}));
export const relations_home = relations(home, ({ one, many }) => ({
  bannerSlides: many(home_banner_slides, {
    relationName: "bannerSlides",
  }),
  about_image: one(media, {
    fields: [home.about_image],
    references: [media.id],
    relationName: "about_image",
  }),
  strategy_axes: many(home_strategy_axes, {
    relationName: "strategy_axes",
  }),
  _locales: many(home_locales, {
    relationName: "_locales",
  }),
}));

type DatabaseSchema = {
  enum__locales: typeof enum__locales;
  enum_pages_status: typeof enum_pages_status;
  enum__pages_v_version_status: typeof enum__pages_v_version_status;
  enum__pages_v_published_locale: typeof enum__pages_v_published_locale;
  enum_news_status: typeof enum_news_status;
  enum__news_v_version_status: typeof enum__news_v_version_status;
  enum__news_v_published_locale: typeof enum__news_v_published_locale;
  enum_signalements_status: typeof enum_signalements_status;
  enum_signalements_province: typeof enum_signalements_province;
  enum_signalements_type_infraction: typeof enum_signalements_type_infraction;
  enum_site_settings_header_nav_children_sub_items_item_type: typeof enum_site_settings_header_nav_children_sub_items_item_type;
  enum_site_settings_header_nav_children_sub_items_nav_link: typeof enum_site_settings_header_nav_children_sub_items_nav_link;
  enum_site_settings_header_nav_children_sub_items_nested_icon: typeof enum_site_settings_header_nav_children_sub_items_nested_icon;
  enum_site_settings_header_nav_children_item_type: typeof enum_site_settings_header_nav_children_item_type;
  enum_site_settings_header_nav_children_nav_link: typeof enum_site_settings_header_nav_children_nav_link;
  enum_site_settings_header_nav_children_nested_icon: typeof enum_site_settings_header_nav_children_nested_icon;
  enum_site_settings_header_nav_item_type: typeof enum_site_settings_header_nav_item_type;
  enum_site_settings_header_nav_nav_link: typeof enum_site_settings_header_nav_nav_link;
  enum_site_settings_header_nav_nested_icon: typeof enum_site_settings_header_nav_nested_icon;
  enum_site_settings_footer_columns_links_nav_link: typeof enum_site_settings_footer_columns_links_nav_link;
  enum_site_settings_footer_social_network: typeof enum_site_settings_footer_social_network;
  enum_site_settings_footer_legal_links_nav_link: typeof enum_site_settings_footer_legal_links_nav_link;
  enum_home_banner_slides_slide_type: typeof enum_home_banner_slides_slide_type;
  enum_home_banner_slides_primary_cta_nav_link: typeof enum_home_banner_slides_primary_cta_nav_link;
  enum_home_banner_slides_secondary_cta_nav_link: typeof enum_home_banner_slides_secondary_cta_nav_link;
  users_sessions: typeof users_sessions;
  users: typeof users;
  media: typeof media;
  signalement_files: typeof signalement_files;
  pages: typeof pages;
  pages_locales: typeof pages_locales;
  _pages_v: typeof _pages_v;
  _pages_v_locales: typeof _pages_v_locales;
  news: typeof news;
  news_locales: typeof news_locales;
  _news_v: typeof _news_v;
  _news_v_locales: typeof _news_v_locales;
  stats: typeof stats;
  stats_locales: typeof stats_locales;
  signalements: typeof signalements;
  signalements_rels: typeof signalements_rels;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  site_settings_header_nav_children_sub_items: typeof site_settings_header_nav_children_sub_items;
  site_settings_header_nav_children_sub_items_locales: typeof site_settings_header_nav_children_sub_items_locales;
  site_settings_header_nav_children: typeof site_settings_header_nav_children;
  site_settings_header_nav_children_locales: typeof site_settings_header_nav_children_locales;
  site_settings_header_nav: typeof site_settings_header_nav;
  site_settings_header_nav_locales: typeof site_settings_header_nav_locales;
  site_settings_footer_columns_links: typeof site_settings_footer_columns_links;
  site_settings_footer_columns_links_locales: typeof site_settings_footer_columns_links_locales;
  site_settings_footer_columns: typeof site_settings_footer_columns;
  site_settings_footer_columns_locales: typeof site_settings_footer_columns_locales;
  site_settings_footer_social: typeof site_settings_footer_social;
  site_settings_footer_legal_links: typeof site_settings_footer_legal_links;
  site_settings_footer_legal_links_locales: typeof site_settings_footer_legal_links_locales;
  site_settings: typeof site_settings;
  site_settings_locales: typeof site_settings_locales;
  home_banner_slides_features: typeof home_banner_slides_features;
  home_banner_slides_features_locales: typeof home_banner_slides_features_locales;
  home_banner_slides: typeof home_banner_slides;
  home_banner_slides_locales: typeof home_banner_slides_locales;
  home_strategy_axes: typeof home_strategy_axes;
  home_strategy_axes_locales: typeof home_strategy_axes_locales;
  home: typeof home;
  home_locales: typeof home_locales;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_media: typeof relations_media;
  relations_signalement_files: typeof relations_signalement_files;
  relations_pages_locales: typeof relations_pages_locales;
  relations_pages: typeof relations_pages;
  relations__pages_v_locales: typeof relations__pages_v_locales;
  relations__pages_v: typeof relations__pages_v;
  relations_news_locales: typeof relations_news_locales;
  relations_news: typeof relations_news;
  relations__news_v_locales: typeof relations__news_v_locales;
  relations__news_v: typeof relations__news_v;
  relations_stats_locales: typeof relations_stats_locales;
  relations_stats: typeof relations_stats;
  relations_signalements_rels: typeof relations_signalements_rels;
  relations_signalements: typeof relations_signalements;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_site_settings_header_nav_children_sub_items_locales: typeof relations_site_settings_header_nav_children_sub_items_locales;
  relations_site_settings_header_nav_children_sub_items: typeof relations_site_settings_header_nav_children_sub_items;
  relations_site_settings_header_nav_children_locales: typeof relations_site_settings_header_nav_children_locales;
  relations_site_settings_header_nav_children: typeof relations_site_settings_header_nav_children;
  relations_site_settings_header_nav_locales: typeof relations_site_settings_header_nav_locales;
  relations_site_settings_header_nav: typeof relations_site_settings_header_nav;
  relations_site_settings_footer_columns_links_locales: typeof relations_site_settings_footer_columns_links_locales;
  relations_site_settings_footer_columns_links: typeof relations_site_settings_footer_columns_links;
  relations_site_settings_footer_columns_locales: typeof relations_site_settings_footer_columns_locales;
  relations_site_settings_footer_columns: typeof relations_site_settings_footer_columns;
  relations_site_settings_footer_social: typeof relations_site_settings_footer_social;
  relations_site_settings_footer_legal_links_locales: typeof relations_site_settings_footer_legal_links_locales;
  relations_site_settings_footer_legal_links: typeof relations_site_settings_footer_legal_links;
  relations_site_settings_locales: typeof relations_site_settings_locales;
  relations_site_settings: typeof relations_site_settings;
  relations_home_banner_slides_features_locales: typeof relations_home_banner_slides_features_locales;
  relations_home_banner_slides_features: typeof relations_home_banner_slides_features;
  relations_home_banner_slides_locales: typeof relations_home_banner_slides_locales;
  relations_home_banner_slides: typeof relations_home_banner_slides;
  relations_home_strategy_axes_locales: typeof relations_home_strategy_axes_locales;
  relations_home_strategy_axes: typeof relations_home_strategy_axes;
  relations_home_locales: typeof relations_home_locales;
  relations_home: typeof relations_home;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
