/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'signalement-files': SignalementFile;
    pages: Page;
    news: News;
    stats: Stat;
    signalements: Signalement;
    'contact-messages': ContactMessage;
    'legislation-documents': LegislationDocument;
    'media-gallery-items': MediaGalleryItem;
    'photo-albums': PhotoAlbum;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'signalement-files': SignalementFilesSelect<false> | SignalementFilesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    signalements: SignalementsSelect<false> | SignalementsSelect<true>;
    'contact-messages': ContactMessagesSelect<false> | ContactMessagesSelect<true>;
    'legislation-documents': LegislationDocumentsSelect<false> | LegislationDocumentsSelect<true>;
    'media-gallery-items': MediaGalleryItemsSelect<false> | MediaGalleryItemsSelect<true>;
    'photo-albums': PhotoAlbumsSelect<false> | PhotoAlbumsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    home: Home;
    'who-we-are': WhoWeAre;
    legislation: Legislation;
    'page-heroes': PageHero;
    'contact-page': ContactPage;
    'press-kit-page': PressKitPage;
    'cartography-settings': CartographySetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    'who-we-are': WhoWeAreSelect<false> | WhoWeAreSelect<true>;
    legislation: LegislationSelect<false> | LegislationSelect<true>;
    'page-heroes': PageHeroesSelect<false> | PageHeroesSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'press-kit-page': PressKitPageSelect<false> | PressKitPageSelect<true>;
    'cartography-settings': CartographySettingsSelect<false> | CartographySettingsSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Optionnel lors d’un upload groupé : laissez vide pour génération automatique (nom du fichier). Utilisez « Modifier tout » dans le tiroir d’upload pour appliquer le même texte à tous les fichiers.
   */
  alt?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    poster?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signalement-files".
 */
export interface SignalementFile {
  id: number;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Chaque page correspond à une URL du site. Renseignez le contenu en français et en anglais (onglets FR / EN). Le slug peut différer par langue (ex. a-propos / about).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Segment d’URL sans slash, par langue. Ex. FR : a-propos — EN : about.
   */
  slug: string;
  /**
   * Court texte affiché sous la bannière (optionnel).
   */
  summary?: string | null;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    media?: (number | null) | Media;
    /**
     * Fond du bandeau en bas de page (section « acteur central »). Repli : bannière du haut.
     */
    ctaMedia?: (number | null) | Media;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentHtml?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Articles publiés sur la page Actualités et dans le carrousel de la page d'accueil. Renseignez le contenu en français et en anglais (onglets FR / EN).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * Généré automatiquement depuis le titre. Modifiez-le pour personnaliser l'URL.
   */
  slug: string;
  /**
   * Court résumé affiché sur la carte et en tête de l'article.
   */
  excerpt: string;
  category:
    | 'inspection'
    | 'cadastre'
    | 'digitalisation'
    | 'conformite'
    | 'communique-presse'
    | 'revue-de-presse'
    | 'custom';
  /**
   * Libellé affiché sur la carte et l'article lorsque « Personnaliser » est sélectionné.
   */
  categoryCustom?: string | null;
  publishedAt: string;
  /**
   * Image affichée sur la carte et en tête de l'article.
   */
  cover?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentHtml?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  /**
   * Ex. provinces, missions, inspecteurs
   */
  key: string;
  label: string;
  value: number;
  /**
   * Ex. +, %, Mois
   */
  suffix?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Signalements transmis via le formulaire public. Les données soumises sont en lecture seule ; seuls le statut de traitement et les notes internes peuvent être modifiés.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signalements".
 */
export interface Signalement {
  id: number;
  reference?: string | null;
  status?: ('recu' | 'en_cours' | 'traite' | 'cloture') | null;
  estAnonyme?: boolean | null;
  alerteur?: {
    nom?: string | null;
    email?: string | null;
    tel?: string | null;
  };
  description: string;
  province?:
    | (
        | 'Bas-Uele'
        | 'Équateur'
        | 'Haut-Katanga'
        | 'Haut-Lomami'
        | 'Haut-Uele'
        | 'Ituri'
        | 'Kasaï'
        | 'Kasaï-Central'
        | 'Kasaï-Oriental'
        | 'Kinshasa'
        | 'Kongo-Central'
        | 'Kwango'
        | 'Kwilu'
        | 'Lomami'
        | 'Lualaba'
        | 'Mai-Ndombe'
        | 'Maniema'
        | 'Mongala'
        | 'Nord-Kivu'
        | 'Nord-Ubangi'
        | 'Sankuru'
        | 'Sud-Kivu'
        | 'Sud-Ubangi'
        | 'Tanganyika'
        | 'Tshopo'
        | 'Tshuapa'
      )
    | null;
  typeInfraction?:
    | (
        | 'Exploitation illégale'
        | 'Contrebande'
        | 'Sous-déclaration'
        | 'Corruption'
        | 'Non-respect des obligations légales'
        | 'Autre'
      )
    | null;
  villeSite?: string | null;
  coords?: string | null;
  pieces?: (number | SignalementFile)[] | null;
  notesInternes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Messages transmis via le formulaire de contact public. Les champs soumis ne sont pas modifiables.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages".
 */
export interface ContactMessage {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  subject: string;
  message: string;
  locale?: ('fr' | 'en') | null;
  status?: ('nouveau' | 'lu') | null;
  notesInternes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Textes officiels (PDF) affichés sur les pages Ordonnances, Lois, Décrets, Arrêtés et Décisions. Uploadez le PDF dans Médias publics puis liez-le ici.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislation-documents".
 */
export interface LegislationDocument {
  id: number;
  title: string;
  /**
   * Page sur laquelle le document sera listé.
   */
  category: 'ordinances' | 'laws' | 'decrees' | 'arretes' | 'decisions';
  /**
   * Ex. Loi n°007/2002, Décret n°23/19…
   */
  reference?: string | null;
  summary?: string | null;
  publishedAt?: string | null;
  /**
   * Plus la valeur est basse, plus le document apparaît en haut.
   */
  order?: number | null;
  /**
   * Le média doit être un PDF (collection Médias publics).
   */
  file: number | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Vidéos affichées sur /videos. Uploadez le fichier dans Médias publics puis liez-le ici. Les photos se gèrent dans « Albums photos ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-gallery-items".
 */
export interface MediaGalleryItem {
  id: number;
  title: string;
  summary?: string | null;
  /**
   * Texte affiché sous la vidéo dans la galerie.
   */
  caption?: string | null;
  publishedAt?: string | null;
  /**
   * Plus la valeur est basse, plus la vidéo apparaît en haut.
   */
  order?: number | null;
  /**
   * Vidéo MP4 (collection Médias publics).
   */
  media: number | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Albums affichés sur /photos. Ajoutez une ou plusieurs images par album (Médias publics). Les vidéos se gèrent dans « Vidéos médiathèque ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-albums".
 */
export interface PhotoAlbum {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  /**
   * URL : /photos/{slug}
   */
  slug: string;
  summary?: string | null;
  /**
   * Optionnel. Repli : première photo de l’album. Utilisée aussi dans le carrousel de la page /photos.
   */
  coverImage?: (number | null) | Media;
  /**
   * Ajoutez les images de l’album. La légende est optionnelle et s’affiche sous la photo dans le visualiseur.
   */
  photos: {
    image: number | Media;
    /**
     * Optionnel. Affichée en bas de la photo lors de la visualisation.
     */
    caption?: string | null;
    id?: string | null;
  }[];
  publishedAt?: string | null;
  /**
   * Plus la valeur est basse, plus l’album apparaît en haut.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'signalement-files';
        value: number | SignalementFile;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'signalements';
        value: number | Signalement;
      } | null)
    | ({
        relationTo: 'contact-messages';
        value: number | ContactMessage;
      } | null)
    | ({
        relationTo: 'legislation-documents';
        value: number | LegislationDocument;
      } | null)
    | ({
        relationTo: 'media-gallery-items';
        value: number | MediaGalleryItem;
      } | null)
    | ({
        relationTo: 'photo-albums';
        value: number | PhotoAlbum;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        poster?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signalement-files_select".
 */
export interface SignalementFilesSelect<T extends boolean = true> {
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        ctaLabel?: T;
        ctaHref?: T;
        media?: T;
        ctaMedia?: T;
      };
  content?: T;
  contentHtml?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  categoryCustom?: T;
  publishedAt?: T;
  cover?: T;
  content?: T;
  contentHtml?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  value?: T;
  suffix?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signalements_select".
 */
export interface SignalementsSelect<T extends boolean = true> {
  reference?: T;
  status?: T;
  estAnonyme?: T;
  alerteur?:
    | T
    | {
        nom?: T;
        email?: T;
        tel?: T;
      };
  description?: T;
  province?: T;
  typeInfraction?: T;
  villeSite?: T;
  coords?: T;
  pieces?: T;
  notesInternes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-messages_select".
 */
export interface ContactMessagesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  subject?: T;
  message?: T;
  locale?: T;
  status?: T;
  notesInternes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislation-documents_select".
 */
export interface LegislationDocumentsSelect<T extends boolean = true> {
  title?: T;
  category?: T;
  reference?: T;
  summary?: T;
  publishedAt?: T;
  order?: T;
  file?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media-gallery-items_select".
 */
export interface MediaGalleryItemsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  caption?: T;
  publishedAt?: T;
  order?: T;
  media?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photo-albums_select".
 */
export interface PhotoAlbumsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  summary?: T;
  coverImage?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  publishedAt?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Coordonnées, menu header et colonnes du pied de page (FR / EN).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  phoneVert?: string | null;
  email?: string | null;
  address?: string | null;
  logo?: (number | null) | Media;
  /**
   * Navigation du header (FR / EN). Laissez vide pour conserver le menu par défaut du site.
   */
  headerNav?:
    | {
        itemType: 'link' | 'dropdown' | 'report';
        label: string;
        navLink?:
          | (
              | '/'
              | '/a-propos'
              | '/historique'
              | '/mission'
              | '/vision'
              | '/organigramme'
              | '/strategie'
              | '/cartographie'
              | '/fraude-miniere'
              | '/contrebande-miniere'
              | '/denoncer'
              | '/sanctions'
              | '/actualites'
              | '/ordonnances'
              | '/lois'
              | '/decrets'
              | '/arretes'
              | '/decisions'
              | '/photos'
              | '/videos'
              | '/dossier-de-presse'
              | '/revue-de-presse'
              | '/contact'
              | '__custom__'
            )
          | null;
        /**
         * Ex. https://…, mailto:…, ou un chemin non listé.
         */
        customHref?: string | null;
        /**
         * Ex. nav-hide-1020, nav-show-1565, nav-show-1020
         */
        cssClass?: string | null;
        nestedIcon?: ('plus' | 'caret') | null;
        /**
         * Visible lorsque le type est « Menu déroulant ».
         */
        children?:
          | {
              itemType: 'link' | 'dropdown' | 'report';
              label: string;
              navLink?:
                | (
                    | '/'
                    | '/a-propos'
                    | '/historique'
                    | '/mission'
                    | '/vision'
                    | '/organigramme'
                    | '/strategie'
                    | '/cartographie'
                    | '/fraude-miniere'
                    | '/contrebande-miniere'
                    | '/denoncer'
                    | '/sanctions'
                    | '/actualites'
                    | '/ordonnances'
                    | '/lois'
                    | '/decrets'
                    | '/arretes'
                    | '/decisions'
                    | '/photos'
                    | '/videos'
                    | '/dossier-de-presse'
                    | '/revue-de-presse'
                    | '/contact'
                    | '__custom__'
                  )
                | null;
              /**
               * Ex. https://…, mailto:…, ou un chemin non listé.
               */
              customHref?: string | null;
              /**
               * Ex. nav-hide-1020, nav-show-1565, nav-show-1020
               */
              cssClass?: string | null;
              nestedIcon?: ('plus' | 'caret') | null;
              /**
               * Visible lorsque le type est « Menu déroulant ».
               */
              subItems?:
                | {
                    itemType: 'link' | 'report';
                    label: string;
                    navLink?:
                      | (
                          | '/'
                          | '/a-propos'
                          | '/historique'
                          | '/mission'
                          | '/vision'
                          | '/organigramme'
                          | '/strategie'
                          | '/cartographie'
                          | '/fraude-miniere'
                          | '/contrebande-miniere'
                          | '/denoncer'
                          | '/sanctions'
                          | '/actualites'
                          | '/ordonnances'
                          | '/lois'
                          | '/decrets'
                          | '/arretes'
                          | '/decisions'
                          | '/photos'
                          | '/videos'
                          | '/dossier-de-presse'
                          | '/revue-de-presse'
                          | '/contact'
                          | '__custom__'
                        )
                      | null;
                    /**
                     * Ex. https://…, mailto:…, ou un chemin non listé.
                     */
                    customHref?: string | null;
                    /**
                     * Ex. nav-hide-1020, nav-show-1565, nav-show-1020
                     */
                    cssClass?: string | null;
                    nestedIcon?: ('plus' | 'caret') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerHqHeading?: string | null;
  footerHqText?: string | null;
  /**
   * Ex. Organes, Liens utiles. Laissez vide pour le contenu par défaut.
   */
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              navLink?:
                | (
                    | '/'
                    | '/a-propos'
                    | '/historique'
                    | '/mission'
                    | '/vision'
                    | '/organigramme'
                    | '/strategie'
                    | '/cartographie'
                    | '/fraude-miniere'
                    | '/contrebande-miniere'
                    | '/denoncer'
                    | '/sanctions'
                    | '/actualites'
                    | '/ordonnances'
                    | '/lois'
                    | '/decrets'
                    | '/arretes'
                    | '/decisions'
                    | '/photos'
                    | '/videos'
                    | '/dossier-de-presse'
                    | '/revue-de-presse'
                    | '/contact'
                    | '__custom__'
                  )
                | null;
              customHref?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerContactTitle?: string | null;
  footerContactLead?: string | null;
  footerContactPhone?: string | null;
  /**
   * Laisser vide pour utiliser l’email général.
   */
  footerContactEmail?: string | null;
  footerSocialTitle?: string | null;
  footerSocial?:
    | {
        network: 'facebook' | 'linkedin' | 'youtube' | 'instagram' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  footerLegalLinks?:
    | {
        label: string;
        navLink?:
          | (
              | '/'
              | '/a-propos'
              | '/historique'
              | '/mission'
              | '/vision'
              | '/organigramme'
              | '/strategie'
              | '/cartographie'
              | '/fraude-miniere'
              | '/contrebande-miniere'
              | '/denoncer'
              | '/sanctions'
              | '/actualites'
              | '/ordonnances'
              | '/lois'
              | '/decrets'
              | '/arretes'
              | '/decisions'
              | '/photos'
              | '/videos'
              | '/dossier-de-presse'
              | '/revue-de-presse'
              | '/contact'
              | '__custom__'
            )
          | null;
        customHref?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex. « Copyright 2026 IGM | All Right Reserved. »
   */
  footerCopyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contenu éditorial de la page d'accueil. Renseignez chaque section en français et en anglais (onglets FR / EN).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  seoTitle?: string | null;
  seoDescription?: string | null;
  bannerSlides?:
    | {
        /**
         * Libellé affiché dans la liste (ex. « Accueil — Mission »). Laissez vide pour utiliser le titre ou « Diapositive 01 ».
         */
        adminLabel?: string | null;
        slideType?: ('image' | 'video') | null;
        image?: (number | null) | Media;
        video?: (number | null) | Media;
        badge?: string | null;
        title: string;
        lead?: string | null;
        features?:
          | {
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        primaryCta?: {
          label?: string | null;
          /**
           * Sélectionnez une page du menu du site.
           */
          navLink?:
            | (
                | '/'
                | '/a-propos'
                | '/historique'
                | '/mission'
                | '/vision'
                | '/organigramme'
                | '/strategie'
                | '/cartographie'
                | '/fraude-miniere'
                | '/contrebande-miniere'
                | '/denoncer'
                | '/sanctions'
                | '/actualites'
                | '/ordonnances'
                | '/lois'
                | '/decrets'
                | '/arretes'
                | '/decisions'
                | '/photos'
                | '/videos'
                | '/dossier-de-presse'
                | '/revue-de-presse'
                | '/contact'
                | '__custom__'
              )
            | null;
          /**
           * Ex. https://…, mailto:…, ou un chemin non listé.
           */
          customHref?: string | null;
        };
        secondaryCta?: {
          label?: string | null;
          /**
           * Sélectionnez une page du menu du site.
           */
          navLink?:
            | (
                | '/'
                | '/a-propos'
                | '/historique'
                | '/mission'
                | '/vision'
                | '/organigramme'
                | '/strategie'
                | '/cartographie'
                | '/fraude-miniere'
                | '/contrebande-miniere'
                | '/denoncer'
                | '/sanctions'
                | '/actualites'
                | '/ordonnances'
                | '/lois'
                | '/decrets'
                | '/arretes'
                | '/decisions'
                | '/photos'
                | '/videos'
                | '/dossier-de-presse'
                | '/revue-de-presse'
                | '/contact'
                | '__custom__'
              )
            | null;
          /**
           * Ex. https://…, mailto:…, ou un chemin non listé.
           */
          customHref?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  about?: {
    title?: string | null;
    leadText?: string | null;
    detailText?: string | null;
    signatureName?: string | null;
    signatureRole?: string | null;
    image?: (number | null) | Media;
  };
  strategy?: {
    /**
     * Vidéo en arrière-plan de la section (MP4 recommandé). Laissez vide pour la vidéo par défaut.
     */
    video?: (number | null) | Media;
    title?: string | null;
    lead?: string | null;
    ambitions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    axesTitle?: string | null;
    axes?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  /**
   * Les valeurs des compteurs sont gérées dans la collection « Chiffres clés ».
   */
  statsSection?: {
    title?: string | null;
    lead?: string | null;
  };
  partnersSection?: {
    title?: string | null;
    partners?:
      | {
          name: string;
          logo: number | Media;
          /**
           * Optionnel — réutilise le logo clair si vide.
           */
          logoDark?: (number | null) | Media;
          /**
           * URL complète (https://…) ou chemin interne (/contact).
           */
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  actionSection?: {
    titlePrefix?: string | null;
    titleHighlight?: string | null;
    titleSuffix?: string | null;
    lead?: string | null;
    items?:
      | {
          /**
           * Saut de ligne pour un retour à la ligne dans le titre.
           */
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaLead?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  /**
   * Remplace l’ancienne section équipe. Le fond bleu du thème est conservé.
   */
  orgChartSection?: {
    titlePrefix?: string | null;
    titleHighlight?: string | null;
    titleSuffix?: string | null;
    lead?: string | null;
    /**
     * Image du schéma complet. Si vide, le schéma officiel du Décret n° 23/19 est affiché automatiquement.
     */
    diagram?: (number | null) | Media;
    units?:
      | {
          name: string;
          role: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    ctaSidebarTitle?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  newsSection?: {
    title?: string | null;
    lead?: string | null;
    /**
     * Articles récents affichés sur la page d'accueil (publiés uniquement).
     */
    maxItems?: number | null;
  };
  /**
   * Titre, texte, bouton et galerie d'images/vidéos affichés en bas de la page d'accueil. Renseignez le contenu en français et en anglais.
   */
  contactSection?: {
    title?: string | null;
    lead?: string | null;
    buttonLabel?: string | null;
    /**
     * Chemin interne (ex. /denoncer, /contact) ou URL absolue. Les liens « dénoncer » ouvrent la modale signalement.
     */
    buttonHref?: string | null;
    /**
     * Images et vidéos à côté du bouton. L'ordre définit l'affichage. Si vide, les visuels par défaut du thème sont utilisés.
     */
    gallery?:
      | {
          kind?: ('image' | 'video') | null;
          image?: (number | null) | Media;
          video?: (number | null) | Media;
          /**
           * Optionnel — ex. 150 ou 190 selon la taille souhaitée.
           */
          displayWidth?: number | null;
          alt?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contenu éditorial de la page Qui sommes-nous (/a-propos). Renseignez chaque section en français et en anglais.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "who-we-are".
 */
export interface WhoWeAre {
  id: number;
  seoTitle?: string | null;
  seoDescription?: string | null;
  /**
   * Titre principal affiché dans le bandeau et dans le fil d'Ariane sur /a-propos.
   */
  heroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  headline?: string | null;
  /**
   * Texte d'accroche (colonne droite).
   */
  intro?: string | null;
  /**
   * Fond du bandeau principal sur /a-propos (et repli sur /historique si non renseigné).
   */
  heroImage?: (number | null) | Media;
  navAboutLabel?: string | null;
  navHistoryLabel?: string | null;
  navMissionLabel?: string | null;
  aboutSection?: {
    /**
     * Optionnel. Laisser vide pour n'afficher aucun titre.
     */
    title?: string | null;
    /**
     * Un paragraphe par ligne.
     */
    body?: string | null;
    image?: (number | null) | Media;
    quote?: {
      text?: string | null;
      authorName?: string | null;
      authorRole?: string | null;
      authorPhoto?: (number | null) | Media;
    };
  };
  historySection?: {
    /**
     * Optionnel. Laisser vide pour n'afficher aucun titre.
     */
    title?: string | null;
    /**
     * Phrase courte affichée dans le bandeau (max. ~70 caractères).
     */
    headline?: string | null;
    /**
     * Optionnel. Court texte d'introduction affiché au-dessus de la frise chronologique sur /a-propos.
     */
    lead?: string | null;
    /**
     * Optionnel. Un paragraphe par ligne. Lignes « • » pour les listes. Liens : [libellé](/chemin).
     */
    timelineIntro?: string | null;
    /**
     * Un paragraphe par ligne. Lignes commençant par « • » pour les listes. Liens : [libellé](/chemin).
     */
    body?: string | null;
    /**
     * Événements affichés dans la frise horizontale sur /a-propos. Cliquer sur l'année ou le titre ouvre la description.
     */
    milestones?:
      | {
          /**
           * Date complète localisée (ex. FR : 9 mars 2018 — EN : 9 March 2018). L'année s'affiche sur la frise ; la date entière dans le modal.
           */
          year?: string | null;
          title?: string | null;
          /**
           * Fond du segment de la frise. Laisser vide (bouton Auto) pour le dégradé bleu automatique.
           */
          segmentColor?: string | null;
          /**
           * Fond du cercle titre. Laisser vide (bouton Auto) pour le style blanc par défaut.
           */
          bubbleColor?: string | null;
          /**
           * Texte affiché dans la fenêtre au clic sur l'année ou le titre.
           */
          text?: string | null;
          /**
           * Bouton affiché sous la description si le libellé et la destination sont renseignés.
           */
          link?: {
            label?: string | null;
            /**
             * Sélectionnez une page du menu du site.
             */
            navLink?:
              | (
                  | '/'
                  | '/a-propos'
                  | '/historique'
                  | '/mission'
                  | '/vision'
                  | '/organigramme'
                  | '/strategie'
                  | '/cartographie'
                  | '/fraude-miniere'
                  | '/contrebande-miniere'
                  | '/denoncer'
                  | '/sanctions'
                  | '/actualites'
                  | '/ordonnances'
                  | '/lois'
                  | '/decrets'
                  | '/arretes'
                  | '/decisions'
                  | '/photos'
                  | '/videos'
                  | '/dossier-de-presse'
                  | '/revue-de-presse'
                  | '/contact'
                  | '__custom__'
                )
              | null;
            /**
             * Ex. https://…, mailto:…, ou un chemin non listé.
             */
            customHref?: string | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Fond du bandeau en haut de /historique. Repli : bannière Introduction.
     */
    heroImage?: (number | null) | Media;
    /**
     * Image de fond du bandeau « acteur central » en bas de /historique.
     */
    ctaImage?: (number | null) | Media;
    /**
     * Première vignette de la section Historique sur /a-propos.
     */
    teaserImage1?: (number | null) | Media;
    /**
     * Deuxième vignette de la section Historique sur /a-propos.
     */
    teaserImage2?: (number | null) | Media;
  };
  missionSection?: {
    /**
     * Grande image à gauche du bloc Mission sur /a-propos.
     */
    image?: (number | null) | Media;
    /**
     * Optionnel. Laisser vide pour n'afficher aucun titre.
     */
    title?: string | null;
    /**
     * Optionnel. Laisser vide pour n'afficher aucun texte.
     */
    lead?: string | null;
    /**
     * Optionnel. Laisser vide pour n'afficher aucun texte.
     */
    headline?: string | null;
    /**
     * Optionnel. Un paragraphe par ligne. Laisser vide pour n'afficher aucun texte.
     */
    body?: string | null;
    /**
     * Optionnel. Laisser vide pour n'afficher aucun titre.
     */
    statutoryTitle?: string | null;
    statutoryItems?:
      | {
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * Optionnel. Laisser vide pour n'afficher aucun titre.
     */
    prioritiesTitle?: string | null;
    priorities?:
      | {
          label?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  statsSection?: {
    items?:
      | {
          label?: string | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  teamSection?: {
    /**
     * Optionnel. Laisser vide pour n'afficher aucun titre.
     */
    title?: string | null;
    lead?: string | null;
    members?:
      | {
          name?: string | null;
          role?: string | null;
          photo?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  ctaSection?: {
    /**
     * Optionnel. Laisser vide pour n'afficher aucun titre.
     */
    title?: string | null;
    text?: string | null;
    link?: {
      label?: string | null;
      /**
       * Sélectionnez une page du menu du site.
       */
      navLink?:
        | (
            | '/'
            | '/a-propos'
            | '/historique'
            | '/mission'
            | '/vision'
            | '/organigramme'
            | '/strategie'
            | '/cartographie'
            | '/fraude-miniere'
            | '/contrebande-miniere'
            | '/denoncer'
            | '/sanctions'
            | '/actualites'
            | '/ordonnances'
            | '/lois'
            | '/decrets'
            | '/arretes'
            | '/decisions'
            | '/photos'
            | '/videos'
            | '/dossier-de-presse'
            | '/revue-de-presse'
            | '/contact'
            | '__custom__'
          )
        | null;
      /**
       * Ex. https://…, mailto:…, ou un chemin non listé.
       */
      customHref?: string | null;
    };
  };
  contactSection?: {
    /**
     * Optionnel. Laisser vide pour n'afficher aucun titre.
     */
    title?: string | null;
    lead?: string | null;
    primaryCta?: {
      label?: string | null;
      /**
       * Sélectionnez une page du menu du site.
       */
      navLink?:
        | (
            | '/'
            | '/a-propos'
            | '/historique'
            | '/mission'
            | '/vision'
            | '/organigramme'
            | '/strategie'
            | '/cartographie'
            | '/fraude-miniere'
            | '/contrebande-miniere'
            | '/denoncer'
            | '/sanctions'
            | '/actualites'
            | '/ordonnances'
            | '/lois'
            | '/decrets'
            | '/arretes'
            | '/decisions'
            | '/photos'
            | '/videos'
            | '/dossier-de-presse'
            | '/revue-de-presse'
            | '/contact'
            | '__custom__'
          )
        | null;
      /**
       * Ex. https://…, mailto:…, ou un chemin non listé.
       */
      customHref?: string | null;
    };
    phoneLabel?: string | null;
    phoneHref?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Bannières des pages Ordonnances, Lois, Décrets, Arrêtés et Décisions : image, titre (H1) et sous-titre.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislation".
 */
export interface Legislation {
  id: number;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  ordinancesHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  ordinancesHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  ordinancesHeroSubtitle?: string | null;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  lawsHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  lawsHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  lawsHeroSubtitle?: string | null;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  decreesHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  decreesHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  decreesHeroSubtitle?: string | null;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  arretesHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  arretesHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  arretesHeroSubtitle?: string | null;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  decisionsHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  decisionsHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  decisionsHeroSubtitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Bannières des pages Présentation, LCFCM, Multimédia (Photos, Vidéos, Revue de presse) : image, titre (H1) et sous-titre si applicable. Contact et Dossier de presse : textes dans leurs globals dédiés. Pages À propos : global « Page À propos ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-heroes".
 */
export interface PageHero {
  id: number;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  orgChartHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  orgChartHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  orgChartHeroSubtitle?: string | null;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  pressKitHeroImage?: (number | null) | Media;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  mapHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  mapHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  mapHeroSubtitle?: string | null;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  strategyHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  strategyHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  strategyHeroSubtitle?: string | null;
  /**
   * Image de fond du bandeau « acteur central » en bas de page. Repli : bannière du haut.
   */
  strategyCtaHeroImage?: (number | null) | Media;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  fraudHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  fraudHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  fraudHeroSubtitle?: string | null;
  /**
   * Image de fond du bandeau « acteur central » en bas de page. Repli : bannière du haut.
   */
  fraudCtaHeroImage?: (number | null) | Media;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  smugglingHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  smugglingHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  smugglingHeroSubtitle?: string | null;
  /**
   * Image de fond du bandeau « acteur central » en bas de page. Repli : bannière du haut.
   */
  smugglingCtaHeroImage?: (number | null) | Media;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  sanctionsHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  sanctionsHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  sanctionsHeroSubtitle?: string | null;
  /**
   * Image de fond du bandeau « acteur central » en bas de page. Repli : bannière du haut.
   */
  sanctionsCtaHeroImage?: (number | null) | Media;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  reportHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  reportHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  reportHeroSubtitle?: string | null;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  contactHeroImage?: (number | null) | Media;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  photosHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  photosHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  photosHeroSubtitle?: string | null;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  videosHeroImage?: (number | null) | Media;
  /**
   * Titre principal et fil d'Ariane.
   */
  videosHeroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  videosHeroSubtitle?: string | null;
  /**
   * Image de fond de la bannière en haut de page (recommandé : paysage, ≥ 1920×600 px).
   */
  pressReviewHeroImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Textes de la page /contact (bannière, formulaire, bloc coordonnées). L’image de bannière se configure dans « Bannières de pages ». Téléphone, e-mail et adresse : « Paramètres du site ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  seoTitle?: string | null;
  seoDescription?: string | null;
  heroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  heroLead?: string | null;
  eyebrow?: string | null;
  formTitle?: string | null;
  infoTitle?: string | null;
  /**
   * Repli : texte « Contact » du pied de page (Paramètres du site).
   */
  infoLead?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * PDF de présentation de l’IGM affiché sur /dossier-de-presse. L’image de bannière se configure dans « Bannières de pages ».
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-kit-page".
 */
export interface PressKitPage {
  id: number;
  seoTitle?: string | null;
  seoDescription?: string | null;
  heroTitle?: string | null;
  /**
   * Optionnel. Laisser vide pour n'afficher aucun sous-titre.
   */
  heroLead?: string | null;
  /**
   * Importez un PDF dans « Médias publics », puis sélectionnez-le ici. Un seul fichier pour toutes les langues.
   */
  presentationPdf?: (number | null) | Media;
  intro?: string | null;
  downloadLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Les provinces déployées sur la carte sont listées automatiquement. Pour chaque province, renseignez l'adresse physique, le téléphone et les inspecteurs (nom obligatoire ; titre, photo et minerais optionnels).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cartography-settings".
 */
export interface CartographySetting {
  id: number;
  /**
   * Une ligne par province couverte sur la carte. Vous ne choisissez pas la province : elle est fixée. Renseignez l'adresse, le téléphone et les inspecteurs.
   */
  provinceAssignments?:
    | {
        province:
          | 'Kinshasa'
          | 'Kongo-Central'
          | 'Kwilu'
          | 'Kasaï'
          | 'Maï-Ndombe'
          | 'Équateur'
          | 'Sud-Ubangi'
          | 'Tshuapa'
          | 'Sankuru'
          | 'Kasaï Oriental'
          | 'Kasaï Central'
          | 'Lualaba'
          | 'Haut-Lomami'
          | 'Tanganyika'
          | 'Kaut-Katanga'
          | 'Sud-Kivu'
          | 'Maniema'
          | 'Tshopo'
          | 'Ituri'
          | 'Nord-Kivu'
          | 'Bas-Uele'
          | 'Haut-Uele';
        physicalAddress?: string | null;
        phone?: string | null;
        inspectors?:
          | {
              name: string;
              title?: string | null;
              photo?: (number | null) | Media;
              /**
               * Ajoutez un ou plusieurs minerais suivis par cet inspecteur.
               */
              minerals?:
                | {
                    name: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  phoneVert?: T;
  email?: T;
  address?: T;
  logo?: T;
  headerNav?:
    | T
    | {
        itemType?: T;
        label?: T;
        navLink?: T;
        customHref?: T;
        cssClass?: T;
        nestedIcon?: T;
        children?:
          | T
          | {
              itemType?: T;
              label?: T;
              navLink?: T;
              customHref?: T;
              cssClass?: T;
              nestedIcon?: T;
              subItems?:
                | T
                | {
                    itemType?: T;
                    label?: T;
                    navLink?: T;
                    customHref?: T;
                    cssClass?: T;
                    nestedIcon?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  footerHqHeading?: T;
  footerHqText?: T;
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              navLink?: T;
              customHref?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  footerContactTitle?: T;
  footerContactLead?: T;
  footerContactPhone?: T;
  footerContactEmail?: T;
  footerSocialTitle?: T;
  footerSocial?:
    | T
    | {
        network?: T;
        url?: T;
        id?: T;
      };
  footerLegalLinks?:
    | T
    | {
        label?: T;
        navLink?: T;
        customHref?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerCopyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  bannerSlides?:
    | T
    | {
        adminLabel?: T;
        slideType?: T;
        image?: T;
        video?: T;
        badge?: T;
        title?: T;
        lead?: T;
        features?:
          | T
          | {
              label?: T;
              id?: T;
            };
        primaryCta?:
          | T
          | {
              label?: T;
              navLink?: T;
              customHref?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              navLink?: T;
              customHref?: T;
            };
        id?: T;
      };
  about?:
    | T
    | {
        title?: T;
        leadText?: T;
        detailText?: T;
        signatureName?: T;
        signatureRole?: T;
        image?: T;
      };
  strategy?:
    | T
    | {
        video?: T;
        title?: T;
        lead?: T;
        ambitions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        axesTitle?: T;
        axes?:
          | T
          | {
              label?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
      };
  statsSection?:
    | T
    | {
        title?: T;
        lead?: T;
      };
  partnersSection?:
    | T
    | {
        title?: T;
        partners?:
          | T
          | {
              name?: T;
              logo?: T;
              logoDark?: T;
              url?: T;
              id?: T;
            };
      };
  actionSection?:
    | T
    | {
        titlePrefix?: T;
        titleHighlight?: T;
        titleSuffix?: T;
        lead?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        ctaLead?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  orgChartSection?:
    | T
    | {
        titlePrefix?: T;
        titleHighlight?: T;
        titleSuffix?: T;
        lead?: T;
        diagram?: T;
        units?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              id?: T;
            };
        ctaSidebarTitle?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  newsSection?:
    | T
    | {
        title?: T;
        lead?: T;
        maxItems?: T;
      };
  contactSection?:
    | T
    | {
        title?: T;
        lead?: T;
        buttonLabel?: T;
        buttonHref?: T;
        gallery?:
          | T
          | {
              kind?: T;
              image?: T;
              video?: T;
              displayWidth?: T;
              alt?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "who-we-are_select".
 */
export interface WhoWeAreSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  heroTitle?: T;
  headline?: T;
  intro?: T;
  heroImage?: T;
  navAboutLabel?: T;
  navHistoryLabel?: T;
  navMissionLabel?: T;
  aboutSection?:
    | T
    | {
        title?: T;
        body?: T;
        image?: T;
        quote?:
          | T
          | {
              text?: T;
              authorName?: T;
              authorRole?: T;
              authorPhoto?: T;
            };
      };
  historySection?:
    | T
    | {
        title?: T;
        headline?: T;
        lead?: T;
        timelineIntro?: T;
        body?: T;
        milestones?:
          | T
          | {
              year?: T;
              title?: T;
              segmentColor?: T;
              bubbleColor?: T;
              text?: T;
              link?:
                | T
                | {
                    label?: T;
                    navLink?: T;
                    customHref?: T;
                  };
              id?: T;
            };
        heroImage?: T;
        ctaImage?: T;
        teaserImage1?: T;
        teaserImage2?: T;
      };
  missionSection?:
    | T
    | {
        image?: T;
        title?: T;
        lead?: T;
        headline?: T;
        body?: T;
        statutoryTitle?: T;
        statutoryItems?:
          | T
          | {
              label?: T;
              id?: T;
            };
        prioritiesTitle?: T;
        priorities?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  statsSection?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  teamSection?:
    | T
    | {
        title?: T;
        lead?: T;
        members?:
          | T
          | {
              name?: T;
              role?: T;
              photo?: T;
              id?: T;
            };
      };
  ctaSection?:
    | T
    | {
        title?: T;
        text?: T;
        link?:
          | T
          | {
              label?: T;
              navLink?: T;
              customHref?: T;
            };
      };
  contactSection?:
    | T
    | {
        title?: T;
        lead?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              navLink?: T;
              customHref?: T;
            };
        phoneLabel?: T;
        phoneHref?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legislation_select".
 */
export interface LegislationSelect<T extends boolean = true> {
  ordinancesHeroImage?: T;
  ordinancesHeroTitle?: T;
  ordinancesHeroSubtitle?: T;
  lawsHeroImage?: T;
  lawsHeroTitle?: T;
  lawsHeroSubtitle?: T;
  decreesHeroImage?: T;
  decreesHeroTitle?: T;
  decreesHeroSubtitle?: T;
  arretesHeroImage?: T;
  arretesHeroTitle?: T;
  arretesHeroSubtitle?: T;
  decisionsHeroImage?: T;
  decisionsHeroTitle?: T;
  decisionsHeroSubtitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-heroes_select".
 */
export interface PageHeroesSelect<T extends boolean = true> {
  orgChartHeroImage?: T;
  orgChartHeroTitle?: T;
  orgChartHeroSubtitle?: T;
  pressKitHeroImage?: T;
  mapHeroImage?: T;
  mapHeroTitle?: T;
  mapHeroSubtitle?: T;
  strategyHeroImage?: T;
  strategyHeroTitle?: T;
  strategyHeroSubtitle?: T;
  strategyCtaHeroImage?: T;
  fraudHeroImage?: T;
  fraudHeroTitle?: T;
  fraudHeroSubtitle?: T;
  fraudCtaHeroImage?: T;
  smugglingHeroImage?: T;
  smugglingHeroTitle?: T;
  smugglingHeroSubtitle?: T;
  smugglingCtaHeroImage?: T;
  sanctionsHeroImage?: T;
  sanctionsHeroTitle?: T;
  sanctionsHeroSubtitle?: T;
  sanctionsCtaHeroImage?: T;
  reportHeroImage?: T;
  reportHeroTitle?: T;
  reportHeroSubtitle?: T;
  contactHeroImage?: T;
  photosHeroImage?: T;
  photosHeroTitle?: T;
  photosHeroSubtitle?: T;
  videosHeroImage?: T;
  videosHeroTitle?: T;
  videosHeroSubtitle?: T;
  pressReviewHeroImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  heroTitle?: T;
  heroLead?: T;
  eyebrow?: T;
  formTitle?: T;
  infoTitle?: T;
  infoLead?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "press-kit-page_select".
 */
export interface PressKitPageSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  heroTitle?: T;
  heroLead?: T;
  presentationPdf?: T;
  intro?: T;
  downloadLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cartography-settings_select".
 */
export interface CartographySettingsSelect<T extends boolean = true> {
  provinceAssignments?:
    | T
    | {
        province?: T;
        physicalAddress?: T;
        phone?: T;
        inspectors?:
          | T
          | {
              name?: T;
              title?: T;
              photo?: T;
              minerals?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}