/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'signalement-files': SignalementFile;
    pages: Page;
    news: News;
    stats: Stat;
    signalements: Signalement;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'signalement-files': SignalementFilesSelect<false> | SignalementFilesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    stats: StatsSelect<false> | StatsSelect<true>;
    signalements: SignalementsSelect<false> | SignalementsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fr' | 'en') | ('fr' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
    home: Home;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: 'fr' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    poster?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signalement-files".
 */
export interface SignalementFile {
  id: number;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Chaque page correspond à une URL du site. Renseignez le contenu en français et en anglais (onglets FR / EN). Le slug peut différer par langue (ex. a-propos / about).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Segment d’URL sans slash, par langue. Ex. FR : a-propos — EN : about.
   */
  slug: string;
  /**
   * Court texte affiché sous la bannière (optionnel).
   */
  summary?: string | null;
  hero?: {
    eyebrow?: string | null;
    title?: string | null;
    lead?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    media?: (number | null) | Media;
  };
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  contentHtml?: string | null;
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Contenu éditorial en français et en anglais (onglets FR / EN).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  category?: string | null;
  publishedAt: string;
  cover?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats".
 */
export interface Stat {
  id: number;
  /**
   * Ex. provinces, missions, inspecteurs
   */
  key: string;
  label: string;
  value: number;
  /**
   * Ex. +, %, Mois
   */
  suffix?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signalements".
 */
export interface Signalement {
  id: number;
  status?: ('recu' | 'en_cours' | 'traite' | 'cloture') | null;
  alerteur?: {
    nom?: string | null;
    email?: string | null;
    tel?: string | null;
  };
  description: string;
  province?:
    | (
        | 'Bas-Uele'
        | 'Équateur'
        | 'Haut-Katanga'
        | 'Haut-Lomami'
        | 'Haut-Uele'
        | 'Ituri'
        | 'Kasaï'
        | 'Kasaï-Central'
        | 'Kasaï-Oriental'
        | 'Kinshasa'
        | 'Kongo-Central'
        | 'Kwango'
        | 'Kwilu'
        | 'Lomami'
        | 'Lualaba'
        | 'Mai-Ndombe'
        | 'Maniema'
        | 'Mongala'
        | 'Nord-Kivu'
        | 'Nord-Ubangi'
        | 'Sankuru'
        | 'Sud-Kivu'
        | 'Sud-Ubangi'
        | 'Tanganyika'
        | 'Tshopo'
        | 'Tshuapa'
      )
    | null;
  villeSite?: string | null;
  coords?: string | null;
  typeInfraction?:
    | (
        | 'Exploitation illégale'
        | 'Contrebande'
        | 'Sous-déclaration'
        | 'Corruption'
        | 'Non-respect des obligations légales'
        | 'Autre'
      )
    | null;
  pieces?: (number | SignalementFile)[] | null;
  notesInternes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'signalement-files';
        value: number | SignalementFile;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'stats';
        value: number | Stat;
      } | null)
    | ({
        relationTo: 'signalements';
        value: number | Signalement;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        poster?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signalement-files_select".
 */
export interface SignalementFilesSelect<T extends boolean = true> {
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  summary?: T;
  hero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lead?: T;
        ctaLabel?: T;
        ctaHref?: T;
        media?: T;
      };
  content?: T;
  contentHtml?: T;
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  category?: T;
  publishedAt?: T;
  cover?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats_select".
 */
export interface StatsSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  value?: T;
  suffix?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signalements_select".
 */
export interface SignalementsSelect<T extends boolean = true> {
  status?: T;
  alerteur?:
    | T
    | {
        nom?: T;
        email?: T;
        tel?: T;
      };
  description?: T;
  province?: T;
  villeSite?: T;
  coords?: T;
  typeInfraction?: T;
  pieces?: T;
  notesInternes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Coordonnées, menu header et colonnes du pied de page (FR / EN).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  phoneVert?: string | null;
  email?: string | null;
  address?: string | null;
  logo?: (number | null) | Media;
  /**
   * Navigation du header (FR / EN). Laissez vide pour conserver le menu par défaut du site.
   */
  headerNav?:
    | {
        itemType: 'link' | 'dropdown' | 'report';
        label: string;
        navLink?:
          | (
              | '/'
              | '/a-propos'
              | '/historique'
              | '/mission'
              | '/vision'
              | '/organigramme'
              | '/cartographie'
              | '/fraude-miniere'
              | '/contrebande-miniere'
              | '/denoncer'
              | '/sanctions'
              | '/actualites'
              | '/ordonnances'
              | '/lois'
              | '/decrets'
              | '/decisions'
              | '/photos'
              | '/videos'
              | '/audios'
              | '/contact'
              | '__custom__'
            )
          | null;
        /**
         * Ex. https://…, mailto:…, ou un chemin non listé.
         */
        customHref?: string | null;
        /**
         * Ex. nav-hide-1020, nav-show-1565, nav-show-1020
         */
        cssClass?: string | null;
        nestedIcon?: ('plus' | 'caret') | null;
        /**
         * Visible lorsque le type est « Menu déroulant ».
         */
        children?:
          | {
              itemType: 'link' | 'dropdown' | 'report';
              label: string;
              navLink?:
                | (
                    | '/'
                    | '/a-propos'
                    | '/historique'
                    | '/mission'
                    | '/vision'
                    | '/organigramme'
                    | '/cartographie'
                    | '/fraude-miniere'
                    | '/contrebande-miniere'
                    | '/denoncer'
                    | '/sanctions'
                    | '/actualites'
                    | '/ordonnances'
                    | '/lois'
                    | '/decrets'
                    | '/decisions'
                    | '/photos'
                    | '/videos'
                    | '/audios'
                    | '/contact'
                    | '__custom__'
                  )
                | null;
              /**
               * Ex. https://…, mailto:…, ou un chemin non listé.
               */
              customHref?: string | null;
              /**
               * Ex. nav-hide-1020, nav-show-1565, nav-show-1020
               */
              cssClass?: string | null;
              nestedIcon?: ('plus' | 'caret') | null;
              /**
               * Visible lorsque le type est « Menu déroulant ».
               */
              subItems?:
                | {
                    itemType: 'link' | 'report';
                    label: string;
                    navLink?:
                      | (
                          | '/'
                          | '/a-propos'
                          | '/historique'
                          | '/mission'
                          | '/vision'
                          | '/organigramme'
                          | '/cartographie'
                          | '/fraude-miniere'
                          | '/contrebande-miniere'
                          | '/denoncer'
                          | '/sanctions'
                          | '/actualites'
                          | '/ordonnances'
                          | '/lois'
                          | '/decrets'
                          | '/decisions'
                          | '/photos'
                          | '/videos'
                          | '/audios'
                          | '/contact'
                          | '__custom__'
                        )
                      | null;
                    /**
                     * Ex. https://…, mailto:…, ou un chemin non listé.
                     */
                    customHref?: string | null;
                    /**
                     * Ex. nav-hide-1020, nav-show-1565, nav-show-1020
                     */
                    cssClass?: string | null;
                    nestedIcon?: ('plus' | 'caret') | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerHqHeading?: string | null;
  footerHqText?: string | null;
  /**
   * Ex. Organes, Liens utiles. Laissez vide pour le contenu par défaut.
   */
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              navLink?:
                | (
                    | '/'
                    | '/a-propos'
                    | '/historique'
                    | '/mission'
                    | '/vision'
                    | '/organigramme'
                    | '/cartographie'
                    | '/fraude-miniere'
                    | '/contrebande-miniere'
                    | '/denoncer'
                    | '/sanctions'
                    | '/actualites'
                    | '/ordonnances'
                    | '/lois'
                    | '/decrets'
                    | '/decisions'
                    | '/photos'
                    | '/videos'
                    | '/audios'
                    | '/contact'
                    | '__custom__'
                  )
                | null;
              customHref?: string | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerContactTitle?: string | null;
  footerContactLead?: string | null;
  footerContactPhone?: string | null;
  /**
   * Laisser vide pour utiliser l’email général.
   */
  footerContactEmail?: string | null;
  footerSocialTitle?: string | null;
  footerSocial?:
    | {
        network: 'facebook' | 'linkedin' | 'youtube' | 'instagram' | 'x';
        url: string;
        id?: string | null;
      }[]
    | null;
  footerLegalLinks?:
    | {
        label: string;
        navLink?:
          | (
              | '/'
              | '/a-propos'
              | '/historique'
              | '/mission'
              | '/vision'
              | '/organigramme'
              | '/cartographie'
              | '/fraude-miniere'
              | '/contrebande-miniere'
              | '/denoncer'
              | '/sanctions'
              | '/actualites'
              | '/ordonnances'
              | '/lois'
              | '/decrets'
              | '/decisions'
              | '/photos'
              | '/videos'
              | '/audios'
              | '/contact'
              | '__custom__'
            )
          | null;
        customHref?: string | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex. « Copyright 2026 IGM | All Right Reserved. »
   */
  footerCopyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Contenu éditorial de la page d'accueil. Renseignez chaque section en français et en anglais (onglets FR / EN).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  seoTitle?: string | null;
  seoDescription?: string | null;
  bannerSlides?:
    | {
        /**
         * Libellé affiché dans la liste (ex. « Accueil — Mission »). Laissez vide pour utiliser le titre ou « Diapositive 01 ».
         */
        adminLabel?: string | null;
        slideType?: ('image' | 'video') | null;
        image?: (number | null) | Media;
        video?: (number | null) | Media;
        badge?: string | null;
        title: string;
        lead?: string | null;
        features?:
          | {
              label?: string | null;
              id?: string | null;
            }[]
          | null;
        primaryCta?: {
          label?: string | null;
          /**
           * Sélectionnez une page du menu du site.
           */
          navLink?:
            | (
                | '/'
                | '/a-propos'
                | '/historique'
                | '/mission'
                | '/vision'
                | '/organigramme'
                | '/cartographie'
                | '/fraude-miniere'
                | '/contrebande-miniere'
                | '/denoncer'
                | '/sanctions'
                | '/actualites'
                | '/ordonnances'
                | '/lois'
                | '/decrets'
                | '/decisions'
                | '/photos'
                | '/videos'
                | '/audios'
                | '/contact'
                | '__custom__'
              )
            | null;
          /**
           * Ex. https://…, mailto:…, ou un chemin non listé.
           */
          customHref?: string | null;
        };
        secondaryCta?: {
          label?: string | null;
          /**
           * Sélectionnez une page du menu du site.
           */
          navLink?:
            | (
                | '/'
                | '/a-propos'
                | '/historique'
                | '/mission'
                | '/vision'
                | '/organigramme'
                | '/cartographie'
                | '/fraude-miniere'
                | '/contrebande-miniere'
                | '/denoncer'
                | '/sanctions'
                | '/actualites'
                | '/ordonnances'
                | '/lois'
                | '/decrets'
                | '/decisions'
                | '/photos'
                | '/videos'
                | '/audios'
                | '/contact'
                | '__custom__'
              )
            | null;
          /**
           * Ex. https://…, mailto:…, ou un chemin non listé.
           */
          customHref?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  about?: {
    title?: string | null;
    mission?: {
      title?: string | null;
      text?: string | null;
      href?: string | null;
    };
    vision?: {
      title?: string | null;
      text?: string | null;
      href?: string | null;
    };
    leadText?: string | null;
    detailText?: string | null;
    signatureName?: string | null;
    signatureRole?: string | null;
    image?: (number | null) | Media;
  };
  strategy?: {
    /**
     * Vidéo en arrière-plan de la section (MP4 recommandé). Laissez vide pour la vidéo par défaut.
     */
    video?: (number | null) | Media;
    title?: string | null;
    lead?: string | null;
    ambitions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    axesTitle?: string | null;
    axes?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  /**
   * Les valeurs des compteurs sont gérées dans la collection « Chiffres clés ».
   */
  statsSection?: {
    title?: string | null;
    lead?: string | null;
  };
  partnersSection?: {
    title?: string | null;
    partners?:
      | {
          name: string;
          logo: number | Media;
          /**
           * Optionnel — réutilise le logo clair si vide.
           */
          logoDark?: (number | null) | Media;
          /**
           * URL complète (https://…) ou chemin interne (/contact).
           */
          url?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  actionSection?: {
    titlePrefix?: string | null;
    titleHighlight?: string | null;
    titleSuffix?: string | null;
    lead?: string | null;
    items?:
      | {
          /**
           * Saut de ligne pour un retour à la ligne dans le titre.
           */
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    ctaLead?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  /**
   * Remplace l’ancienne section équipe. Le fond bleu du thème est conservé.
   */
  orgChartSection?: {
    titlePrefix?: string | null;
    titleHighlight?: string | null;
    titleSuffix?: string | null;
    lead?: string | null;
    /**
     * Image du schéma complet. Si vide, le schéma officiel du Décret n° 23/19 est affiché automatiquement.
     */
    diagram?: (number | null) | Media;
    units?:
      | {
          name: string;
          role: string;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
    ctaSidebarTitle?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  newsSection?: {
    title?: string | null;
    lead?: string | null;
    maxItems?: number | null;
  };
  contactSection?: {
    title?: string | null;
    lead?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  phoneVert?: T;
  email?: T;
  address?: T;
  logo?: T;
  headerNav?:
    | T
    | {
        itemType?: T;
        label?: T;
        navLink?: T;
        customHref?: T;
        cssClass?: T;
        nestedIcon?: T;
        children?:
          | T
          | {
              itemType?: T;
              label?: T;
              navLink?: T;
              customHref?: T;
              cssClass?: T;
              nestedIcon?: T;
              subItems?:
                | T
                | {
                    itemType?: T;
                    label?: T;
                    navLink?: T;
                    customHref?: T;
                    cssClass?: T;
                    nestedIcon?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  footerHqHeading?: T;
  footerHqText?: T;
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              navLink?: T;
              customHref?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  footerContactTitle?: T;
  footerContactLead?: T;
  footerContactPhone?: T;
  footerContactEmail?: T;
  footerSocialTitle?: T;
  footerSocial?:
    | T
    | {
        network?: T;
        url?: T;
        id?: T;
      };
  footerLegalLinks?:
    | T
    | {
        label?: T;
        navLink?: T;
        customHref?: T;
        openInNewTab?: T;
        id?: T;
      };
  footerCopyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  seoTitle?: T;
  seoDescription?: T;
  bannerSlides?:
    | T
    | {
        adminLabel?: T;
        slideType?: T;
        image?: T;
        video?: T;
        badge?: T;
        title?: T;
        lead?: T;
        features?:
          | T
          | {
              label?: T;
              id?: T;
            };
        primaryCta?:
          | T
          | {
              label?: T;
              navLink?: T;
              customHref?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              navLink?: T;
              customHref?: T;
            };
        id?: T;
      };
  about?:
    | T
    | {
        title?: T;
        mission?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
            };
        vision?:
          | T
          | {
              title?: T;
              text?: T;
              href?: T;
            };
        leadText?: T;
        detailText?: T;
        signatureName?: T;
        signatureRole?: T;
        image?: T;
      };
  strategy?:
    | T
    | {
        video?: T;
        title?: T;
        lead?: T;
        ambitions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        axesTitle?: T;
        axes?:
          | T
          | {
              label?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
      };
  statsSection?:
    | T
    | {
        title?: T;
        lead?: T;
      };
  partnersSection?:
    | T
    | {
        title?: T;
        partners?:
          | T
          | {
              name?: T;
              logo?: T;
              logoDark?: T;
              url?: T;
              id?: T;
            };
      };
  actionSection?:
    | T
    | {
        titlePrefix?: T;
        titleHighlight?: T;
        titleSuffix?: T;
        lead?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        ctaLead?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  orgChartSection?:
    | T
    | {
        titlePrefix?: T;
        titleHighlight?: T;
        titleSuffix?: T;
        lead?: T;
        diagram?: T;
        units?:
          | T
          | {
              name?: T;
              role?: T;
              image?: T;
              id?: T;
            };
        ctaSidebarTitle?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  newsSection?:
    | T
    | {
        title?: T;
        lead?: T;
        maxItems?: T;
      };
  contactSection?:
    | T
    | {
        title?: T;
        lead?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}